// Code generated by test/parity/testdata/latex-upstream-cases.mjs; DO NOT EDIT.
package latex

import "testing"

func TestUpstreamRenderLatex(t *testing.T) {
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:18
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\mathbb{C}^3 \\\\to \\\\mathbb{C}^3\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\mathbb{C}^3 \\to \\mathbb{C}^3", RenderLatexOptions{Display: false}); ok != true || got != "ℂ³ → ℂ³" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\mathbb{C}^3 \\to \\mathbb{C}^3", got, ok, "ℂ³ → ℂ³", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:19
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\{3x+2y,\\\\; 27x^2-4z-1,\\\\; x(x-1)(x+1)\\\\} \\\\quad\\\\Rightarrow\\\\quad x \\\\in \\\\{0, \\\\pm 1\\\\},\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\{3x+2y,\\; 27x^2-4z-1,\\; x(x-1)(x+1)\\} \\quad\\Rightarrow\\quad x \\in \\{0, \\pm 1\\},", RenderLatexOptions{Display: false}); ok != true || got != "{3x+2y, 27x²-4z-1, x(x-1)(x+1)} ⇒ x ∈ {0, ± 1}," {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\{3x+2y,\\; 27x^2-4z-1,\\; x(x-1)(x+1)\\} \\quad\\Rightarrow\\quad x \\in \\{0, \\pm 1\\},", got, ok, "{3x+2y, 27x²-4z-1, x(x-1)(x+1)} ⇒ x ∈ {0, ± 1},", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:23
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"F_1 = -\\\\frac{1}{4x^2}.\"", func(t *testing.T) {
		if got, ok := RenderLatex("F_1 = -\\frac{1}{4x^2}.", RenderLatexOptions{Display: false}); ok != true || got != "F₁ = -1/(4x²)." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "F_1 = -\\frac{1}{4x^2}.", got, ok, "F₁ = -1/(4x²).", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:24
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"-2\"", func(t *testing.T) {
		if got, ok := RenderLatex("-2", RenderLatexOptions{Display: false}); ok != true || got != "-2" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "-2", got, ok, "-2", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:25
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"(0,0,-1/4)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(0,0,-1/4)", RenderLatexOptions{Display: false}); ok != true || got != "(0,0,-1/4)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(0,0,-1/4)", got, ok, "(0,0,-1/4)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:26
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"(1,-3/2,13/2)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(1,-3/2,13/2)", RenderLatexOptions{Display: false}); ok != true || got != "(1,-3/2,13/2)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(1,-3/2,13/2)", got, ok, "(1,-3/2,13/2)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:27
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"(1,1,1)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(1,1,1)", RenderLatexOptions{Display: false}); ok != true || got != "(1,1,1)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(1,1,1)", got, ok, "(1,1,1)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:28
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"(2,1,0)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(2,1,0)", RenderLatexOptions{Display: false}); ok != true || got != "(2,1,0)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(2,1,0)", got, ok, "(2,1,0)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:29
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"(-1/4, 0, 0)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(-1/4, 0, 0)", RenderLatexOptions{Display: false}); ok != true || got != "(-1/4, 0, 0)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(-1/4, 0, 0)", got, ok, "(-1/4, 0, 0)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:30
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\{(0,0,-1/4), (1,-3/2,13/2), (-1,3/2,13/2)\\\\}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\{(0,0,-1/4), (1,-3/2,13/2), (-1,3/2,13/2)\\}", RenderLatexOptions{Display: false}); ok != true || got != "{(0,0,-1/4), (1,-3/2,13/2), (-1,3/2,13/2)}" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\{(0,0,-1/4), (1,-3/2,13/2), (-1,3/2,13/2)\\}", got, ok, "{(0,0,-1/4), (1,-3/2,13/2), (-1,3/2,13/2)}", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:31
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"(2,1,1)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(2,1,1)", RenderLatexOptions{Display: false}); ok != true || got != "(2,1,1)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(2,1,1)", got, ok, "(2,1,1)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:32
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"(7/3,-2/5,11/7)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(7/3,-2/5,11/7)", RenderLatexOptions{Display: false}); ok != true || got != "(7/3,-2/5,11/7)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(7/3,-2/5,11/7)", got, ok, "(7/3,-2/5,11/7)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:33
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\{y - p(x),\\\\; q(x)\\\\}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\{y - p(x),\\; q(x)\\}", RenderLatexOptions{Display: false}); ok != true || got != "{y - p(x), q(x)}" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\{y - p(x),\\; q(x)\\}", got, ok, "{y - p(x), q(x)}", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:34
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\deg q = 3\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\deg q = 3", RenderLatexOptions{Display: false}); ok != true || got != "deg q = 3" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\deg q = 3", got, ok, "deg q = 3", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:35
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"[\\\\mathbb{C}(x,y,z):\\\\mathbb{C}(F_1,F_2,F_3)] = 3\"", func(t *testing.T) {
		if got, ok := RenderLatex("[\\mathbb{C}(x,y,z):\\mathbb{C}(F_1,F_2,F_3)] = 3", RenderLatexOptions{Display: false}); ok != true || got != "[ℂ(x,y,z):ℂ(F₁,F₂,F₃)] = 3" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "[\\mathbb{C}(x,y,z):\\mathbb{C}(F_1,F_2,F_3)] = 3", got, ok, "[ℂ(x,y,z):ℂ(F₁,F₂,F₃)] = 3", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:36
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"u = 1+xy\"", func(t *testing.T) {
		if got, ok := RenderLatex("u = 1+xy", RenderLatexOptions{Display: false}); ok != true || got != "u = 1+xy" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "u = 1+xy", got, ok, "u = 1+xy", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:37
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"G = u^2 z + y^2(4+3xy)\"", func(t *testing.T) {
		if got, ok := RenderLatex("G = u^2 z + y^2(4+3xy)", RenderLatexOptions{Display: false}); ok != true || got != "G = u² z + y²(4+3xy)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "G = u^2 z + y^2(4+3xy)", got, ok, "G = u² z + y²(4+3xy)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:38
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"F_1 = uG\"", func(t *testing.T) {
		if got, ok := RenderLatex("F_1 = uG", RenderLatexOptions{Display: false}); ok != true || got != "F₁ = uG" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "F_1 = uG", got, ok, "F₁ = uG", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:39
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"F_2 = y + 3xG\"", func(t *testing.T) {
		if got, ok := RenderLatex("F_2 = y + 3xG", RenderLatexOptions{Display: false}); ok != true || got != "F₂ = y + 3xG" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "F_2 = y + 3xG", got, ok, "F₂ = y + 3xG", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:40
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"x=0\"", func(t *testing.T) {
		if got, ok := RenderLatex("x=0", RenderLatexOptions{Display: false}); ok != true || got != "x = 0" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x=0", got, ok, "x = 0", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:41
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"F_2 = F_3 = 0\"", func(t *testing.T) {
		if got, ok := RenderLatex("F_2 = F_3 = 0", RenderLatexOptions{Display: false}); ok != true || got != "F₂ = F₃ = 0" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "F_2 = F_3 = 0", got, ok, "F₂ = F₃ = 0", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:42
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"xy = -3/2\"", func(t *testing.T) {
		if got, ok := RenderLatex("xy = -3/2", RenderLatexOptions{Display: false}); ok != true || got != "xy = -3/2" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "xy = -3/2", got, ok, "xy = -3/2", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:43
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"x^2 z = 13/2\"", func(t *testing.T) {
		if got, ok := RenderLatex("x^2 z = 13/2", RenderLatexOptions{Display: false}); ok != true || got != "x² z = 13/2" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x^2 z = 13/2", got, ok, "x² z = 13/2", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:44
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\mathbb{C}^*\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\mathbb{C}^*", RenderLatexOptions{Display: false}); ok != true || got != "ℂ^*" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\mathbb{C}^*", got, ok, "ℂ^*", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:45
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"s \\\\mapsto (s,\\\\, -\\\\tfrac{3}{2s},\\\\, \\\\tfrac{13}{2s^2})\"", func(t *testing.T) {
		if got, ok := RenderLatex("s \\mapsto (s,\\, -\\tfrac{3}{2s},\\, \\tfrac{13}{2s^2})", RenderLatexOptions{Display: false}); ok != true || got != "s ↦ (s, -3/(2s), 13/(2s²))" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "s \\mapsto (s,\\, -\\tfrac{3}{2s},\\, \\tfrac{13}{2s^2})", got, ok, "s ↦ (s, -3/(2s), 13/(2s²))", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:46
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"X\"", func(t *testing.T) {
		if got, ok := RenderLatex("X", RenderLatexOptions{Display: false}); ok != true || got != "X" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "X", got, ok, "X", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:47
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"p_\\\\pm\"", func(t *testing.T) {
		if got, ok := RenderLatex("p_\\pm", RenderLatexOptions{Display: false}); ok != true || got != "p_±" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "p_\\pm", got, ok, "p_±", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:48
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"F(-x,-y,z) = (F_1, -F_2, -F_3)\"", func(t *testing.T) {
		if got, ok := RenderLatex("F(-x,-y,z) = (F_1, -F_2, -F_3)", RenderLatexOptions{Display: false}); ok != true || got != "F(-x,-y,z) = (F₁, -F₂, -F₃)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "F(-x,-y,z) = (F_1, -F_2, -F_3)", got, ok, "F(-x,-y,z) = (F₁, -F₂, -F₃)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:49
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"p_0\"", func(t *testing.T) {
		if got, ok := RenderLatex("p_0", RenderLatexOptions{Display: false}); ok != true || got != "p₀" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "p_0", got, ok, "p₀", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:50
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"s \\\\to \\\\infty\"", func(t *testing.T) {
		if got, ok := RenderLatex("s \\to \\infty", RenderLatexOptions{Display: false}); ok != true || got != "s → ∞" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "s \\to \\infty", got, ok, "s → ∞", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:51
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"(0,0,0)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(0,0,0)", RenderLatexOptions{Display: false}); ok != true || got != "(0,0,0)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(0,0,0)", got, ok, "(0,0,0)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:52
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\Rightarrow\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\Rightarrow", RenderLatexOptions{Display: false}); ok != true || got != "⇒" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\Rightarrow", got, ok, "⇒", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:53
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\ge 2\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\ge 2", RenderLatexOptions{Display: false}); ok != true || got != "≥ 2" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\ge 2", got, ok, "≥ 2", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:54
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\ge 3\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\ge 3", RenderLatexOptions{Display: false}); ok != true || got != "≥ 3" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\ge 3", got, ok, "≥ 3", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:55
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"1\"", func(t *testing.T) {
		if got, ok := RenderLatex("1", RenderLatexOptions{Display: false}); ok != true || got != "1" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "1", got, ok, "1", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:56
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"\\\\mathrm{diag}(-1/2,1,1),\\\\quad F_{\\\\rm intrinsic}(\\\\lambda)\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\mathrm{diag}(-1/2,1,1),\\quad F_{\\rm intrinsic}(\\lambda)", RenderLatexOptions{Display: false}); ok != true || got != "diag(-1/2,1,1), F_intrinsic(λ)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\mathrm{diag}(-1/2,1,1),\\quad F_{\\rm intrinsic}(\\lambda)", got, ok, "diag(-1/2,1,1), F_intrinsic(λ)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:57
	t.Run("renderLatex/Jacobian conjecture session using dollar delimiters/renders \"4+3xy\"", func(t *testing.T) {
		if got, ok := RenderLatex("4+3xy", RenderLatexOptions{Display: false}); ok != true || got != "4+3xy" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "4+3xy", got, ok, "4+3xy", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:63
	t.Run("renderLatex/satellite calculation session using bracket delimiters/renders \"E \\\\approx \\\\frac{0.1\\\\ \\\\text{lux}}{100\\\\ \\\\text{lm/W}} = 0.001\\\\ \\\\text{W/m}^2\"", func(t *testing.T) {
		if got, ok := RenderLatex("E \\approx \\frac{0.1\\ \\text{lux}}{100\\ \\text{lm/W}} = 0.001\\ \\text{W/m}^2", RenderLatexOptions{Display: false}); ok != true || got != "E ≈ (0.1 lux)/(100 lm/W) = 0.001 W/m²" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "E \\approx \\frac{0.1\\ \\text{lux}}{100\\ \\text{lm/W}} = 0.001\\ \\text{W/m}^2", got, ok, "E ≈ (0.1 lux)/(100 lm/W) = 0.001 W/m²", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:67
	t.Run("renderLatex/satellite calculation session using bracket delimiters/renders \"\\\\boxed{1\\\\ \\\\text{milliwatt per square metre}}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\boxed{1\\ \\text{milliwatt per square metre}}", RenderLatexOptions{Display: false}); ok != true || got != "[1 milliwatt per square metre]" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\boxed{1\\ \\text{milliwatt per square metre}}", got, ok, "[1 milliwatt per square metre]", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:68
	t.Run("renderLatex/satellite calculation session using bracket delimiters/renders \"5\\\\ \\\\text{km}^2 = 5{,}000{,}000\\\\ \\\\text{m}^2\"", func(t *testing.T) {
		if got, ok := RenderLatex("5\\ \\text{km}^2 = 5{,}000{,}000\\ \\text{m}^2", RenderLatexOptions{Display: false}); ok != true || got != "5 km² = 5,000,000 m²" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "5\\ \\text{km}^2 = 5{,}000{,}000\\ \\text{m}^2", got, ok, "5 km² = 5,000,000 m²", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:69
	t.Run("renderLatex/satellite calculation session using bracket delimiters/renders \"P_{\\\\text{light}} = 0.001 \\\\times 5{,}000{,}000\\n= \\\\boxed{5{,}000\\\\ \\\\text{W}}\"", func(t *testing.T) {
		if got, ok := RenderLatex("P_{\\text{light}} = 0.001 \\times 5{,}000{,}000\n= \\boxed{5{,}000\\ \\text{W}}", RenderLatexOptions{Display: false}); ok != true || got != "P_light = 0.001 × 5,000,000 = [5,000 W]" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "P_{\\text{light}} = 0.001 \\times 5{,}000{,}000\n= \\boxed{5{,}000\\ \\text{W}}", got, ok, "P_light = 0.001 × 5,000,000 = [5,000 W]", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:74
	t.Run("renderLatex/satellite calculation session using bracket delimiters/renders \"P_{\\\\text{electric}} = 5\\\\ \\\\text{kW} \\\\times 0.2\\n= \\\\boxed{1\\\\ \\\\text{kW}}\"", func(t *testing.T) {
		if got, ok := RenderLatex("P_{\\text{electric}} = 5\\ \\text{kW} \\times 0.2\n= \\boxed{1\\ \\text{kW}}", RenderLatexOptions{Display: false}); ok != true || got != "P_electric = 5 kW × 0.2 = [1 kW]" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "P_{\\text{electric}} = 5\\ \\text{kW} \\times 0.2\n= \\boxed{1\\ \\text{kW}}", got, ok, "P_electric = 5 kW × 0.2 = [1 kW]", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:79
	t.Run("renderLatex/satellite calculation session using bracket delimiters/renders \"\\\\pi(2.5\\\\ \\\\text{km})^2 = 19.6\\\\ \\\\text{km}^2\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\pi(2.5\\ \\text{km})^2 = 19.6\\ \\text{km}^2", RenderLatexOptions{Display: false}); ok != true || got != "π(2.5 km)² = 19.6 km²" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\pi(2.5\\ \\text{km})^2 = 19.6\\ \\text{km}^2", got, ok, "π(2.5 km)² = 19.6 km²", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:80
	t.Run("renderLatex/satellite calculation session using bracket delimiters/renders \"0.001\\\\ \\\\text{W/m}^2 \\\\times 19.6 \\\\times 10^6\\\\ \\\\text{m}^2\\n\\\\approx \\\\boxed{20\\\\ \\\\text{kW optical}}\"", func(t *testing.T) {
		if got, ok := RenderLatex("0.001\\ \\text{W/m}^2 \\times 19.6 \\times 10^6\\ \\text{m}^2\n\\approx \\boxed{20\\ \\text{kW optical}}", RenderLatexOptions{Display: false}); ok != true || got != "0.001 W/m² × 19.6 × 10⁶ m² ≈ [20 kW optical]" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "0.001\\ \\text{W/m}^2 \\times 19.6 \\times 10^6\\ \\text{m}^2\n\\approx \\boxed{20\\ \\text{kW optical}}", got, ok, "0.001 W/m² × 19.6 × 10⁶ m² ≈ [20 kW optical]", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:85
	t.Run("renderLatex/satellite calculation session using bracket delimiters/renders \"1\\\\ \\\\text{kW} \\\\times \\\\frac{1}{3600}\\\\ \\\\text{hour}\\n= \\\\boxed{0.28\\\\ \\\\text{Wh}}\"", func(t *testing.T) {
		if got, ok := RenderLatex("1\\ \\text{kW} \\times \\frac{1}{3600}\\ \\text{hour}\n= \\boxed{0.28\\ \\text{Wh}}", RenderLatexOptions{Display: false}); ok != true || got != "1 kW × 1/3600 hour = [0.28 Wh]" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "1\\ \\text{kW} \\times \\frac{1}{3600}\\ \\text{hour}\n= \\boxed{0.28\\ \\text{Wh}}", got, ok, "1 kW × 1/3600 hour = [0.28 Wh]", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:95
	t.Run("renderLatex/Jacobian conjecture sessions using parenthesis and bracket delimiters/renders \"\\\\det\\\\!\\\\left(\\\\frac{\\\\partial(F_1,F_2,F_3)}{\\\\partial(x,y,z)}\\\\right)=-2.\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\det\\!\\left(\\frac{\\partial(F_1,F_2,F_3)}{\\partial(x,y,z)}\\right)=-2.", RenderLatexOptions{Display: false}); ok != true || got != "det((∂(F₁,F₂,F₃))/(∂(x,y,z))) = -2." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\det\\!\\left(\\frac{\\partial(F_1,F_2,F_3)}{\\partial(x,y,z)}\\right)=-2.", got, ok, "det((∂(F₁,F₂,F₃))/(∂(x,y,z))) = -2.", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:99
	t.Run("renderLatex/Jacobian conjecture sessions using parenthesis and bracket delimiters/renders \"\\\\begin{aligned}\\nF(0,0,-\\\\tfrac14)&=(-\\\\tfrac14,0,0),\\\\\\\\\\nF(1,-\\\\tfrac32,\\\\tfrac{13}2)&=(-\\\\tfrac14,0,0),\\\\\\\\\\nF(-1,\\\\tfrac32,\\\\tfrac{13}2)&=(-\\\\tfrac14,0,0).\\n\\\\end{aligned}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\begin{aligned}\nF(0,0,-\\tfrac14)&=(-\\tfrac14,0,0),\\\\\nF(1,-\\tfrac32,\\tfrac{13}2)&=(-\\tfrac14,0,0),\\\\\nF(-1,\\tfrac32,\\tfrac{13}2)&=(-\\tfrac14,0,0).\n\\end{aligned}", RenderLatexOptions{Display: false}); ok != true || got != "F(0,0,-1/4) = (-1/4,0,0),\nF(1,-3/2,13/2) = (-1/4,0,0),\nF(-1,3/2,13/2) = (-1/4,0,0)." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\begin{aligned}\nF(0,0,-\\tfrac14)&=(-\\tfrac14,0,0),\\\\\nF(1,-\\tfrac32,\\tfrac{13}2)&=(-\\tfrac14,0,0),\\\\\nF(-1,\\tfrac32,\\tfrac{13}2)&=(-\\tfrac14,0,0).\n\\end{aligned}", got, ok, "F(0,0,-1/4) = (-1/4,0,0),\nF(1,-3/2,13/2) = (-1/4,0,0),\nF(-1,3/2,13/2) = (-1/4,0,0).", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:107
	t.Run("renderLatex/Jacobian conjecture sessions using parenthesis and bracket delimiters/renders \"F=(F_1,F_2,F_3)\"", func(t *testing.T) {
		if got, ok := RenderLatex("F=(F_1,F_2,F_3)", RenderLatexOptions{Display: false}); ok != true || got != "F = (F₁,F₂,F₃)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "F=(F_1,F_2,F_3)", got, ok, "F = (F₁,F₂,F₃)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:108
	t.Run("renderLatex/Jacobian conjecture sessions using parenthesis and bracket delimiters/renders \"F\"", func(t *testing.T) {
		if got, ok := RenderLatex("F", RenderLatexOptions{Display: false}); ok != true || got != "F" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "F", got, ok, "F", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:109
	t.Run("renderLatex/Jacobian conjecture sessions using parenthesis and bracket delimiters/renders \"3\"", func(t *testing.T) {
		if got, ok := RenderLatex("3", RenderLatexOptions{Display: false}); ok != true || got != "3" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "3", got, ok, "3", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:115
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"J = \\\\begin{pmatrix}\\n\\\\frac{\\\\partial f_1}{\\\\partial x} & \\\\frac{\\\\partial f_1}{\\\\partial y} & \\\\frac{\\\\partial f_1}{\\\\partial z} \\\\\\\\\\n\\\\frac{\\\\partial f_2}{\\\\partial x} & \\\\frac{\\\\partial f_2}{\\\\partial y} & \\\\frac{\\\\partial f_2}{\\\\partial z} \\\\\\\\\\n\\\\frac{\\\\partial f_3}{\\\\partial x} & \\\\frac{\\\\partial f_3}{\\\\partial y} & \\\\frac{\\\\partial f_3}{\\\\partial z}\\n\\\\end{pmatrix}\"", func(t *testing.T) {
		if got, ok := RenderLatex("J = \\begin{pmatrix}\n\\frac{\\partial f_1}{\\partial x} & \\frac{\\partial f_1}{\\partial y} & \\frac{\\partial f_1}{\\partial z} \\\\\n\\frac{\\partial f_2}{\\partial x} & \\frac{\\partial f_2}{\\partial y} & \\frac{\\partial f_2}{\\partial z} \\\\\n\\frac{\\partial f_3}{\\partial x} & \\frac{\\partial f_3}{\\partial y} & \\frac{\\partial f_3}{\\partial z}\n\\end{pmatrix}", RenderLatexOptions{Display: false}); ok != true || got != "J = ⎛ (∂ f₁)/(∂ x) │ (∂ f₁)/(∂ y) │ (∂ f₁)/(∂ z) ⎞\n    ⎜ (∂ f₂)/(∂ x) │ (∂ f₂)/(∂ y) │ (∂ f₂)/(∂ z) ⎟\n    ⎝ (∂ f₃)/(∂ x) │ (∂ f₃)/(∂ y) │ (∂ f₃)/(∂ z) ⎠" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "J = \\begin{pmatrix}\n\\frac{\\partial f_1}{\\partial x} & \\frac{\\partial f_1}{\\partial y} & \\frac{\\partial f_1}{\\partial z} \\\\\n\\frac{\\partial f_2}{\\partial x} & \\frac{\\partial f_2}{\\partial y} & \\frac{\\partial f_2}{\\partial z} \\\\\n\\frac{\\partial f_3}{\\partial x} & \\frac{\\partial f_3}{\\partial y} & \\frac{\\partial f_3}{\\partial z}\n\\end{pmatrix}", got, ok, "J = ⎛ (∂ f₁)/(∂ x) │ (∂ f₁)/(∂ y) │ (∂ f₁)/(∂ z) ⎞\n    ⎜ (∂ f₂)/(∂ x) │ (∂ f₂)/(∂ y) │ (∂ f₂)/(∂ z) ⎟\n    ⎝ (∂ f₃)/(∂ x) │ (∂ f₃)/(∂ y) │ (∂ f₃)/(∂ z) ⎠", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:123
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"\\\\begin{aligned}\\nf_1 &= (1+xy)^3 z + y^2(1+xy)(4+3xy) \\\\\\\\\\nf_2 &= y + 3x(1+xy)^2 z + 3xy^2(4+3xy) \\\\\\\\\\nf_3 &= 2x - 3x^2y - x^3z\\n\\\\end{aligned}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\begin{aligned}\nf_1 &= (1+xy)^3 z + y^2(1+xy)(4+3xy) \\\\\nf_2 &= y + 3x(1+xy)^2 z + 3xy^2(4+3xy) \\\\\nf_3 &= 2x - 3x^2y - x^3z\n\\end{aligned}", RenderLatexOptions{Display: false}); ok != true || got != "f₁ = (1+xy)³ z + y²(1+xy)(4+3xy)\nf₂ = y + 3x(1+xy)² z + 3xy²(4+3xy)\nf₃ = 2x - 3x²y - x³z" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\begin{aligned}\nf_1 &= (1+xy)^3 z + y^2(1+xy)(4+3xy) \\\\\nf_2 &= y + 3x(1+xy)^2 z + 3xy^2(4+3xy) \\\\\nf_3 &= 2x - 3x^2y - x^3z\n\\end{aligned}", got, ok, "f₁ = (1+xy)³ z + y²(1+xy)(4+3xy)\nf₂ = y + 3x(1+xy)² z + 3xy²(4+3xy)\nf₃ = 2x - 3x²y - x³z", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:131
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"x, y, z\"", func(t *testing.T) {
		if got, ok := RenderLatex("x, y, z", RenderLatexOptions{Display: false}); ok != true || got != "x, y, z" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x, y, z", got, ok, "x, y, z", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:132
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"(x, y, z)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(x, y, z)", RenderLatexOptions{Display: false}); ok != true || got != "(x, y, z)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(x, y, z)", got, ok, "(x, y, z)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:133
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"(0,\\\\; 0,\\\\; -\\\\tfrac14)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(0,\\; 0,\\; -\\tfrac14)", RenderLatexOptions{Display: false}); ok != true || got != "(0, 0, -1/4)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(0,\\; 0,\\; -\\tfrac14)", got, ok, "(0, 0, -1/4)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:134
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"(-\\\\tfrac14,\\\\; 0,\\\\; 0)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(-\\tfrac14,\\; 0,\\; 0)", RenderLatexOptions{Display: false}); ok != true || got != "(-1/4, 0, 0)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(-\\tfrac14,\\; 0,\\; 0)", got, ok, "(-1/4, 0, 0)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:135
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"(1,\\\\; -\\\\tfrac32,\\\\; \\\\tfrac{13}{2})\"", func(t *testing.T) {
		if got, ok := RenderLatex("(1,\\; -\\tfrac32,\\; \\tfrac{13}{2})", RenderLatexOptions{Display: false}); ok != true || got != "(1, -3/2, 13/2)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(1,\\; -\\tfrac32,\\; \\tfrac{13}{2})", got, ok, "(1, -3/2, 13/2)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:136
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"(-1,\\\\; \\\\tfrac32,\\\\; \\\\tfrac{13}{2})\"", func(t *testing.T) {
		if got, ok := RenderLatex("(-1,\\; \\tfrac32,\\; \\tfrac{13}{2})", RenderLatexOptions{Display: false}); ok != true || got != "(-1, 3/2, 13/2)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(-1,\\; \\tfrac32,\\; \\tfrac{13}{2})", got, ok, "(-1, 3/2, 13/2)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:137
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"(-\\\\frac14, 0, 0)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(-\\frac14, 0, 0)", RenderLatexOptions{Display: false}); ok != true || got != "(-1/4, 0, 0)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(-\\frac14, 0, 0)", got, ok, "(-1/4, 0, 0)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:138
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"F: \\\\mathbb{C}^3 \\\\to \\\\mathbb{C}^3\"", func(t *testing.T) {
		if got, ok := RenderLatex("F: \\mathbb{C}^3 \\to \\mathbb{C}^3", RenderLatexOptions{Display: false}); ok != true || got != "F: ℂ³ → ℂ³" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "F: \\mathbb{C}^3 \\to \\mathbb{C}^3", got, ok, "F: ℂ³ → ℂ³", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:139
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"F(0,0,-\\\\tfrac14) = F(1,-\\\\tfrac32,\\\\tfrac{13}{2}) = F(-1,\\\\tfrac32,\\\\tfrac{13}{2}) = (-\\\\tfrac14, 0, 0)\"", func(t *testing.T) {
		if got, ok := RenderLatex("F(0,0,-\\tfrac14) = F(1,-\\tfrac32,\\tfrac{13}{2}) = F(-1,\\tfrac32,\\tfrac{13}{2}) = (-\\tfrac14, 0, 0)", RenderLatexOptions{Display: false}); ok != true || got != "F(0,0,-1/4) = F(1,-3/2,13/2) = F(-1,3/2,13/2) = (-1/4, 0, 0)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "F(0,0,-\\tfrac14) = F(1,-\\tfrac32,\\tfrac{13}{2}) = F(-1,\\tfrac32,\\tfrac{13}{2}) = (-\\tfrac14, 0, 0)", got, ok, "F(0,0,-1/4) = F(1,-3/2,13/2) = F(-1,3/2,13/2) = (-1/4, 0, 0)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:143
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"\\\\mathbb{C}^3\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\mathbb{C}^3", RenderLatexOptions{Display: false}); ok != true || got != "ℂ³" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\mathbb{C}^3", got, ok, "ℂ³", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:144
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"\\\\begin{aligned}\\nf_1 &= \\\\frac{f_1^{\\\\text{ut}}(u,t)}{x^2}, \\\\quad\\nf_2 = \\\\frac{f_2^{\\\\text{ut}}(u,t)}{x}, \\\\quad\\nf_3 = x\\\\,(2 - 3u - t)\\n\\\\end{aligned}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\begin{aligned}\nf_1 &= \\frac{f_1^{\\text{ut}}(u,t)}{x^2}, \\quad\nf_2 = \\frac{f_2^{\\text{ut}}(u,t)}{x}, \\quad\nf_3 = x\\,(2 - 3u - t)\n\\end{aligned}", RenderLatexOptions{Display: false}); ok != true || got != "f₁ = (f₁ᵘᵗ(u,t))/(x²), f₂ = (f₂ᵘᵗ(u,t))/x, f₃ = x (2 - 3u - t)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\begin{aligned}\nf_1 &= \\frac{f_1^{\\text{ut}}(u,t)}{x^2}, \\quad\nf_2 = \\frac{f_2^{\\text{ut}}(u,t)}{x}, \\quad\nf_3 = x\\,(2 - 3u - t)\n\\end{aligned}", got, ok, "f₁ = (f₁ᵘᵗ(u,t))/(x²), f₂ = (f₂ᵘᵗ(u,t))/x, f₃ = x (2 - 3u - t)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:152
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"\\\\det J_F\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\det J_F", RenderLatexOptions{Display: false}); ok != true || got != "det J_F" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\det J_F", got, ok, "det J_F", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:153
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"(-\\\\tfrac14, 0, 0)\"", func(t *testing.T) {
		if got, ok := RenderLatex("(-\\tfrac14, 0, 0)", RenderLatexOptions{Display: false}); ok != true || got != "(-1/4, 0, 0)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "(-\\tfrac14, 0, 0)", got, ok, "(-1/4, 0, 0)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:154
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"u = xy\"", func(t *testing.T) {
		if got, ok := RenderLatex("u = xy", RenderLatexOptions{Display: false}); ok != true || got != "u = xy" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "u = xy", got, ok, "u = xy", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:155
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"t = x^2z\"", func(t *testing.T) {
		if got, ok := RenderLatex("t = x^2z", RenderLatexOptions{Display: false}); ok != true || got != "t = x²z" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "t = x^2z", got, ok, "t = x²z", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:156
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"x \\\\neq 0\"", func(t *testing.T) {
		if got, ok := RenderLatex("x \\neq 0", RenderLatexOptions{Display: false}); ok != true || got != "x ≠ 0" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x \\neq 0", got, ok, "x ≠ 0", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:157
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"f_1^{\\\\text{ut}}, f_2^{\\\\text{ut}}\"", func(t *testing.T) {
		if got, ok := RenderLatex("f_1^{\\text{ut}}, f_2^{\\text{ut}}", RenderLatexOptions{Display: false}); ok != true || got != "f₁ᵘᵗ, f₂ᵘᵗ" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "f_1^{\\text{ut}}, f_2^{\\text{ut}}", got, ok, "f₁ᵘᵗ, f₂ᵘᵗ", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:158
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"u,t\"", func(t *testing.T) {
		if got, ok := RenderLatex("u,t", RenderLatexOptions{Display: false}); ok != true || got != "u,t" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "u,t", got, ok, "u,t", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:159
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"x\"", func(t *testing.T) {
		if got, ok := RenderLatex("x", RenderLatexOptions{Display: false}); ok != true || got != "x" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x", got, ok, "x", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:160
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"x, x^2\"", func(t *testing.T) {
		if got, ok := RenderLatex("x, x^2", RenderLatexOptions{Display: false}); ok != true || got != "x, x²" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x, x^2", got, ok, "x, x²", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:161
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"\\\\mathbb{C}^n \\\\to \\\\mathbb{C}^n\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\mathbb{C}^n \\to \\mathbb{C}^n", RenderLatexOptions{Display: false}); ok != true || got != "ℂⁿ → ℂⁿ" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\mathbb{C}^n \\to \\mathbb{C}^n", got, ok, "ℂⁿ → ℂⁿ", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:162
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"n \\\\geq 2\"", func(t *testing.T) {
		if got, ok := RenderLatex("n \\geq 2", RenderLatexOptions{Display: false}); ok != true || got != "n ≥ 2" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "n \\geq 2", got, ok, "n ≥ 2", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:163
	t.Run("renderLatex/Jacobian matrix session using dollar delimiters/renders \"\\\\mathbb{P}^3\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\mathbb{P}^3", RenderLatexOptions{Display: false}); ok != true || got != "ℙ³" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\mathbb{P}^3", got, ok, "ℙ³", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:169
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"e^{i\\\\pi}+1=0\"", func(t *testing.T) {
		if got, ok := RenderLatex("e^{i\\pi}+1=0", RenderLatexOptions{Display: false}); ok != true || got != "e^(iπ)+1 = 0" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "e^{i\\pi}+1=0", got, ok, "e^(iπ)+1 = 0", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:170
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\boxed{\\n\\\\mathcal{Z}(\\\\beta)\\n=\\n\\\\int_{\\\\mathcal M}\\n\\\\exp\\\\!\\\\left(\\n-\\\\beta\\\\left[\\n\\\\frac12 g^{ij}(x)\\\\,\\\\partial_i\\\\phi\\\\,\\\\partial_j\\\\phi\\n+V(\\\\phi)\\n\\\\right]\\\\right)\\n\\\\mathcal D\\\\phi\\n}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\boxed{\n\\mathcal{Z}(\\beta)\n=\n\\int_{\\mathcal M}\n\\exp\\!\\left(\n-\\beta\\left[\n\\frac12 g^{ij}(x)\\,\\partial_i\\phi\\,\\partial_j\\phi\n+V(\\phi)\n\\right]\\right)\n\\mathcal D\\phi\n}", RenderLatexOptions{Display: false}); ok != true || got != "[Z(β) = ∫_M exp( -β[ 1/2 gⁱʲ(x) ∂ᵢϕ ∂ⱼϕ +V(ϕ) ]) Dϕ]" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\boxed{\n\\mathcal{Z}(\\beta)\n=\n\\int_{\\mathcal M}\n\\exp\\!\\left(\n-\\beta\\left[\n\\frac12 g^{ij}(x)\\,\\partial_i\\phi\\,\\partial_j\\phi\n+V(\\phi)\n\\right]\\right)\n\\mathcal D\\phi\n}", got, ok, "[Z(β) = ∫_M exp( -β[ 1/2 gⁱʲ(x) ∂ᵢϕ ∂ⱼϕ +V(ϕ) ]) Dϕ]", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:184
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\begin{aligned}\\n\\\\nabla_\\\\mu T^{\\\\mu\\\\nu}\\n&=\\n\\\\frac{1}{\\\\sqrt{-g}}\\n\\\\partial_\\\\mu\\\\!\\\\left(\\\\sqrt{-g}\\\\,T^{\\\\mu\\\\nu}\\\\right)\\n+\\\\Gamma^\\\\nu_{\\\\mu\\\\lambda}T^{\\\\mu\\\\lambda}\\n=0, \\\\\\\\[4pt]\\nR_{\\\\mu\\\\nu}-\\\\frac12 Rg_{\\\\mu\\\\nu}+\\\\Lambda g_{\\\\mu\\\\nu}\\n&=\\n\\\\frac{8\\\\pi G}{c^4}T_{\\\\mu\\\\nu}.\\n\\\\end{aligned}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\begin{aligned}\n\\nabla_\\mu T^{\\mu\\nu}\n&=\n\\frac{1}{\\sqrt{-g}}\n\\partial_\\mu\\!\\left(\\sqrt{-g}\\,T^{\\mu\\nu}\\right)\n+\\Gamma^\\nu_{\\mu\\lambda}T^{\\mu\\lambda}\n=0, \\\\[4pt]\nR_{\\mu\\nu}-\\frac12 Rg_{\\mu\\nu}+\\Lambda g_{\\mu\\nu}\n&=\n\\frac{8\\pi G}{c^4}T_{\\mu\\nu}.\n\\end{aligned}", RenderLatexOptions{Display: false}); ok != true || got != "∇_μ T^(μν) = 1/(√(-g)) ∂_μ(√(-g) T^(μν)) +Γ^ν_(μλ)T^(μλ) = 0,\nR_(μν)-1/2 Rg_(μν)+Λ g_(μν) = (8π G)/(c⁴)T_(μν)." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\begin{aligned}\n\\nabla_\\mu T^{\\mu\\nu}\n&=\n\\frac{1}{\\sqrt{-g}}\n\\partial_\\mu\\!\\left(\\sqrt{-g}\\,T^{\\mu\\nu}\\right)\n+\\Gamma^\\nu_{\\mu\\lambda}T^{\\mu\\lambda}\n=0, \\\\[4pt]\nR_{\\mu\\nu}-\\frac12 Rg_{\\mu\\nu}+\\Lambda g_{\\mu\\nu}\n&=\n\\frac{8\\pi G}{c^4}T_{\\mu\\nu}.\n\\end{aligned}", got, ok, "∇_μ T^(μν) = 1/(√(-g)) ∂_μ(√(-g) T^(μν)) +Γ^ν_(μλ)T^(μλ) = 0,\nR_(μν)-1/2 Rg_(μν)+Λ g_(μν) = (8π G)/(c⁴)T_(μν).", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:198
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"f(z)\\n=\\n\\\\frac{1}{2\\\\pi i}\\n\\\\oint_{\\\\gamma}\\n\\\\frac{f(\\\\zeta)}{\\\\zeta-z}\\\\,d\\\\zeta,\\n\\\\qquad\\n\\\\det\\\\!\\\\begin{pmatrix}\\n\\\\lambda-a & -b & 0\\\\\\\\\\n-c & \\\\lambda-d & -e\\\\\\\\\\n0 & -f & \\\\lambda-g\\n\\\\end{pmatrix}\\n=0.\"", func(t *testing.T) {
		if got, ok := RenderLatex("f(z)\n=\n\\frac{1}{2\\pi i}\n\\oint_{\\gamma}\n\\frac{f(\\zeta)}{\\zeta-z}\\,d\\zeta,\n\\qquad\n\\det\\!\\begin{pmatrix}\n\\lambda-a & -b & 0\\\\\n-c & \\lambda-d & -e\\\\\n0 & -f & \\lambda-g\n\\end{pmatrix}\n=0.", RenderLatexOptions{Display: false}); ok != true || got != "f(z) = 1/(2π i) ∮_γ (f(ζ))/(ζ-z) dζ, det⎛ λ-a │ -b  │ 0   ⎞ = 0.\n                                        ⎜ -c  │ λ-d │ -e  ⎟\n                                        ⎝ 0   │ -f  │ λ-g ⎠" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "f(z)\n=\n\\frac{1}{2\\pi i}\n\\oint_{\\gamma}\n\\frac{f(\\zeta)}{\\zeta-z}\\,d\\zeta,\n\\qquad\n\\det\\!\\begin{pmatrix}\n\\lambda-a & -b & 0\\\\\n-c & \\lambda-d & -e\\\\\n0 & -f & \\lambda-g\n\\end{pmatrix}\n=0.", got, ok, "f(z) = 1/(2π i) ∮_γ (f(ζ))/(ζ-z) dζ, det⎛ λ-a │ -b  │ 0   ⎞ = 0.\n                                        ⎜ -c  │ λ-d │ -e  ⎟\n                                        ⎝ 0   │ -f  │ λ-g ⎠", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:217
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\Psi(x,t)=\\n\\\\sum_{n=1}^{\\\\infty}\\n\\\\underbrace{\\nc_n\\n\\\\sqrt{\\\\frac{2}{L}}\\n\\\\sin\\\\!\\\\left(\\\\frac{n\\\\pi x}{L}\\\\right)\\n}_{\\\\text{spatial eigenmode}}\\n\\\\exp\\\\!\\\\left(-\\\\frac{i\\\\hbar n^2\\\\pi^2}{2mL^2}t\\\\right),\\n\\\\qquad\\n|\\\\Psi(x,t)|^2\\n=\\n\\\\begin{cases}\\n\\\\Psi^\\\\ast\\\\Psi, & 0<x<L,\\\\\\\\\\n0, & \\\\text{otherwise}.\\n\\\\end{cases}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\Psi(x,t)=\n\\sum_{n=1}^{\\infty}\n\\underbrace{\nc_n\n\\sqrt{\\frac{2}{L}}\n\\sin\\!\\left(\\frac{n\\pi x}{L}\\right)\n}_{\\text{spatial eigenmode}}\n\\exp\\!\\left(-\\frac{i\\hbar n^2\\pi^2}{2mL^2}t\\right),\n\\qquad\n|\\Psi(x,t)|^2\n=\n\\begin{cases}\n\\Psi^\\ast\\Psi, & 0<x<L,\\\\\n0, & \\text{otherwise}.\n\\end{cases}", RenderLatexOptions{Display: false}); ok != true || got != "                                                                                                 ⎧ Ψ^∗Ψ if 0 < x < L,\nΨ(x,t) = ∑ₙ₌₁^∞ cₙ √(2/L) sin((nπ x)/L)_(spatial eigenmode) exp(-(iℏ n²π²)/(2mL²)t), |Ψ(x,t)|² = ⎨\n                                                                                                 ⎩ 0    otherwise." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\Psi(x,t)=\n\\sum_{n=1}^{\\infty}\n\\underbrace{\nc_n\n\\sqrt{\\frac{2}{L}}\n\\sin\\!\\left(\\frac{n\\pi x}{L}\\right)\n}_{\\text{spatial eigenmode}}\n\\exp\\!\\left(-\\frac{i\\hbar n^2\\pi^2}{2mL^2}t\\right),\n\\qquad\n|\\Psi(x,t)|^2\n=\n\\begin{cases}\n\\Psi^\\ast\\Psi, & 0<x<L,\\\\\n0, & \\text{otherwise}.\n\\end{cases}", got, ok, "                                                                                                 ⎧ Ψ^∗Ψ if 0 < x < L,\nΨ(x,t) = ∑ₙ₌₁^∞ cₙ √(2/L) sin((nπ x)/L)_(spatial eigenmode) exp(-(iℏ n²π²)/(2mL²)t), |Ψ(x,t)|² = ⎨\n                                                                                                 ⎩ 0    otherwise.", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:235
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"x=\\\\frac{-b\\\\pm\\\\sqrt{b^2-4ac}}{2a}\"", func(t *testing.T) {
		if got, ok := RenderLatex("x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}", RenderLatexOptions{Display: false}); ok != true || got != "x = (-b±√(b²-4ac))/(2a)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}", got, ok, "x = (-b±√(b²-4ac))/(2a)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:236
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\int_0^\\\\infty e^{-x^2}\\\\,dx=\\\\frac{\\\\sqrt{\\\\pi}}{2}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\int_0^\\infty e^{-x^2}\\,dx=\\frac{\\sqrt{\\pi}}{2}", RenderLatexOptions{Display: false}); ok != true || got != "∫₀^∞ e^(-x²) dx = (√π)/2" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\int_0^\\infty e^{-x^2}\\,dx=\\frac{\\sqrt{\\pi}}{2}", got, ok, "∫₀^∞ e^(-x²) dx = (√π)/2", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:237
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"e^{i\\\\theta}=\\\\cos\\\\theta+i\\\\sin\\\\theta\"", func(t *testing.T) {
		if got, ok := RenderLatex("e^{i\\theta}=\\cos\\theta+i\\sin\\theta", RenderLatexOptions{Display: false}); ok != true || got != "e^(iθ) = cos θ+i sin θ" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "e^{i\\theta}=\\cos\\theta+i\\sin\\theta", got, ok, "e^(iθ) = cos θ+i sin θ", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:238
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\sum_{n=1}^{\\\\infty}\\\\frac{1}{n^2}=\\\\frac{\\\\pi^2}{6}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\sum_{n=1}^{\\infty}\\frac{1}{n^2}=\\frac{\\pi^2}{6}", RenderLatexOptions{Display: false}); ok != true || got != "∑ₙ₌₁^∞1/(n²) = π²/6" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\sum_{n=1}^{\\infty}\\frac{1}{n^2}=\\frac{\\pi^2}{6}", got, ok, "∑ₙ₌₁^∞1/(n²) = π²/6", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:239
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\lim_{x\\\\to 0}\\\\frac{\\\\sin x}{x}=1\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\lim_{x\\to 0}\\frac{\\sin x}{x}=1", RenderLatexOptions{Display: false}); ok != true || got != "lim[x→0] (sin x)/x = 1" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\lim_{x\\to 0}\\frac{\\sin x}{x}=1", got, ok, "lim[x→0] (sin x)/x = 1", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:240
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\lim_{n\\\\to\\\\infty}\\n\\\\left(1+\\\\frac{1}{n}\\\\right)^n=e\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\lim_{n\\to\\infty}\n\\left(1+\\frac{1}{n}\\right)^n=e", RenderLatexOptions{Display: false}); ok != true || got != "lim[n→∞] (1+1/n)ⁿ = e" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\lim_{n\\to\\infty}\n\\left(1+\\frac{1}{n}\\right)^n=e", got, ok, "lim[n→∞] (1+1/n)ⁿ = e", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:245
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\int_0^1 \\\\frac{x^2}{1+x^3}\\\\,dx\\n=\\\\frac{1}{3}\\\\ln 2\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\int_0^1 \\frac{x^2}{1+x^3}\\,dx\n=\\frac{1}{3}\\ln 2", RenderLatexOptions{Display: false}); ok != true || got != "∫₀¹ x²/(1+x³) dx = 1/3 ln 2" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\int_0^1 \\frac{x^2}{1+x^3}\\,dx\n=\\frac{1}{3}\\ln 2", got, ok, "∫₀¹ x²/(1+x³) dx = 1/3 ln 2", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:250
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\sum_{k=1}^{n}\\\\frac{k}{k+1}\\n=n+1-H_{n+1}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\sum_{k=1}^{n}\\frac{k}{k+1}\n=n+1-H_{n+1}", RenderLatexOptions{Display: false}); ok != true || got != "∑ₖ₌₁ⁿk/(k+1) = n+1-Hₙ₊₁" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\sum_{k=1}^{n}\\frac{k}{k+1}\n=n+1-H_{n+1}", got, ok, "∑ₖ₌₁ⁿk/(k+1) = n+1-Hₙ₊₁", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:255
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\frac{\\n  \\\\displaystyle \\\\frac{x^2+1}{x-1}\\n  -\\n  \\\\displaystyle \\\\frac{2x}{x+1}\\n}{\\n  \\\\displaystyle \\\\frac{x}{x^2-1}\\n}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\frac{\n  \\displaystyle \\frac{x^2+1}{x-1}\n  -\n  \\displaystyle \\frac{2x}{x+1}\n}{\n  \\displaystyle \\frac{x}{x^2-1}\n}", RenderLatexOptions{Display: false}); ok != true || got != "((x²+1)/(x-1) - 2x/(x+1))/(x/(x²-1))" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\frac{\n  \\displaystyle \\frac{x^2+1}{x-1}\n  -\n  \\displaystyle \\frac{2x}{x+1}\n}{\n  \\displaystyle \\frac{x}{x^2-1}\n}", got, ok, "((x²+1)/(x-1) - 2x/(x+1))/(x/(x²-1))", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:265
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\lim_{x\\\\to 0}\\n\\\\frac{\\n  \\\\displaystyle \\\\frac{\\\\sin x}{x}-1\\n}{\\n  \\\\displaystyle \\\\frac{e^x-1}{x}-1\\n}\\n=0\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\lim_{x\\to 0}\n\\frac{\n  \\displaystyle \\frac{\\sin x}{x}-1\n}{\n  \\displaystyle \\frac{e^x-1}{x}-1\n}\n=0", RenderLatexOptions{Display: false}); ok != true || got != "lim[x→0] ((sin x)/x-1)/((eˣ-1)/x-1) = 0" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\lim_{x\\to 0}\n\\frac{\n  \\displaystyle \\frac{\\sin x}{x}-1\n}{\n  \\displaystyle \\frac{e^x-1}{x}-1\n}\n=0", got, ok, "lim[x→0] ((sin x)/x-1)/((eˣ-1)/x-1) = 0", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:275
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\frac{\\n  1+\\\\displaystyle\\\\frac{1}{1+\\\\frac{1}{x}}\\n}{\\n  1-\\\\displaystyle\\\\frac{1}{1-\\\\frac{1}{x}}\\n}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\frac{\n  1+\\displaystyle\\frac{1}{1+\\frac{1}{x}}\n}{\n  1-\\displaystyle\\frac{1}{1-\\frac{1}{x}}\n}", RenderLatexOptions{Display: false}); ok != true || got != "(1+1/(1+1/x))/(1-1/(1-1/x))" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\frac{\n  1+\\displaystyle\\frac{1}{1+\\frac{1}{x}}\n}{\n  1-\\displaystyle\\frac{1}{1-\\frac{1}{x}}\n}", got, ok, "(1+1/(1+1/x))/(1-1/(1-1/x))", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:283
	t.Run("renderLatex/extended formulas from a renderer stress-test session/renders \"\\\\sum_{n=1}^{\\\\infty}\\n\\\\frac{\\n  \\\\displaystyle \\\\frac{1}{n}-\\\\frac{1}{n+1}\\n}{\\n  \\\\displaystyle 1+\\\\frac{1}{n^2}\\n}\"", func(t *testing.T) {
		if got, ok := RenderLatex("\\sum_{n=1}^{\\infty}\n\\frac{\n  \\displaystyle \\frac{1}{n}-\\frac{1}{n+1}\n}{\n  \\displaystyle 1+\\frac{1}{n^2}\n}", RenderLatexOptions{Display: false}); ok != true || got != "∑ₙ₌₁^∞ (1/n-1/(n+1))/(1+1/(n²))" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\sum_{n=1}^{\\infty}\n\\frac{\n  \\displaystyle \\frac{1}{n}-\\frac{1}{n+1}\n}{\n  \\displaystyle 1+\\frac{1}{n^2}\n}", got, ok, "∑ₙ₌₁^∞ (1/n-1/(n+1))/(1+1/(n²))", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:295
	t.Run("renderLatex/renders common symbols, roots, sums, and integrals", func(t *testing.T) {
		if got, ok := RenderLatex("\\sum_{i=0}^n \\alpha_i + \\int_0^\\infty e^{-x^2}\\,dx = \\sqrt{\\pi}", RenderLatexOptions{Display: false}); ok != true || got != "∑ᵢ₌₀ⁿ αᵢ + ∫₀^∞ e^(-x²) dx = √π" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\sum_{i=0}^n \\alpha_i + \\int_0^\\infty e^{-x^2}\\,dx = \\sqrt{\\pi}", got, ok, "∑ᵢ₌₀ⁿ αᵢ + ∫₀^∞ e^(-x²) dx = √π", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:302
	t.Run("renderLatex/renders common accents and binomial notation", func(t *testing.T) {
		if got, ok := RenderLatex("\\binom{n}{k}+\\vec{x}+\\hat{y}+\\overline{AB}", RenderLatexOptions{Display: false}); ok != true || got != "(n choose k)+x⃗+ŷ+overline(AB)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\binom{n}{k}+\\vec{x}+\\hat{y}+\\overline{AB}", got, ok, "(n choose k)+x⃗+ŷ+overline(AB)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:309
	t.Run("renderLatex/renders extended symbols and negated relations", func(t *testing.T) {
		if got, ok := RenderLatex("\\epsilon+\\varepsilon+\\varsigma+\\varkappa+\\oplus+\\otimes+\\therefore+\\because", RenderLatexOptions{Display: false}); ok != true || got != "ϵ+ε+ς+ϰ+⊕+⊗+∴+∵" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\epsilon+\\varepsilon+\\varsigma+\\varkappa+\\oplus+\\otimes+\\therefore+\\because", got, ok, "ϵ+ε+ς+ϰ+⊕+⊗+∴+∵", true)
		}
		if got, ok := RenderLatex("A\\not\\subseteq B,\\quad x\\not\\in X", RenderLatexOptions{Display: false}); ok != true || got != "A ⊈ B, x ∉ X" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "A\\not\\subseteq B,\\quad x\\not\\in X", got, ok, "A ⊈ B, x ∉ X", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:317
	t.Run("renderLatex/renders relational algebra join operators", func(t *testing.T) {
		if got, ok := RenderLatex("R\\bowtie S,\\quad R\\Join S", RenderLatexOptions{Display: false}); ok != true || got != "R ⋈ S, R ⋈ S" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "R\\bowtie S,\\quad R\\Join S", got, ok, "R ⋈ S, R ⋈ S", true)
		}
		if got, ok := RenderLatex("R\\ltimes S,\\quad R\\rtimes S", RenderLatexOptions{Display: false}); ok != true || got != "R ⋉ S, R ⋊ S" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "R\\ltimes S,\\quad R\\rtimes S", got, ok, "R ⋉ S, R ⋊ S", true)
		}
		if got, ok := RenderLatex("R\\leftouterjoin S,\\quad R\\rightouterjoin S,\\quad R\\fullouterjoin S", RenderLatexOptions{Display: false}); ok != true || got != "R ⟕ S, R ⟖ S, R ⟗ S" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "R\\leftouterjoin S,\\quad R\\rightouterjoin S,\\quad R\\fullouterjoin S", got, ok, "R ⟕ S, R ⟖ S, R ⟗ S", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:326
	t.Run("renderLatex/renders delimiter commands and invisible delimiters", func(t *testing.T) {
		if got, ok := RenderLatex("\\lvert{x}\\rvert+\\lVert{v}\\rVert+\\left.\\frac{dy}{dx}\\right|_{x=0}", RenderLatexOptions{Display: false}); ok != true || got != "|x|+‖v‖+dy/(dx)|ₓ₌₀" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\lvert{x}\\rvert+\\lVert{v}\\rVert+\\left.\\frac{dy}{dx}\\right|_{x=0}", got, ok, "|x|+‖v‖+dy/(dx)|ₓ₌₀", true)
		}
		if got, ok := RenderLatex("\\left\\lbrace x \\middle| x>0 \\right\\rbrace", RenderLatexOptions{Display: false}); ok != true || got != "{ x | x > 0 }" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\left\\lbrace x \\middle| x>0 \\right\\rbrace", got, ok, "{ x | x > 0 }", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:334
	t.Run("renderLatex/renders named, modular, overlaid, and underlaid operators", func(t *testing.T) {
		if got, ok := RenderLatex("\\operatorname*{arg\\,max}_{x\\in X} f(x)", RenderLatexOptions{Display: false}); ok != true || got != "arg max[x∈X] f(x)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\operatorname*{arg\\,max}_{x\\in X} f(x)", got, ok, "arg max[x∈X] f(x)", true)
		}
		if got, ok := RenderLatex("a\\bmod n,\\quad a\\equiv b\\pmod n", RenderLatexOptions{Display: false}); ok != true || got != "a mod n, a ≡ b (mod n)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "a\\bmod n,\\quad a\\equiv b\\pmod n", got, ok, "a mod n, a ≡ b (mod n)", true)
		}
		if got, ok := RenderLatex("\\overset{!}{=}+\\underset{n}{x}+\\stackrel{def}{=}", RenderLatexOptions{Display: false}); ok != true || got != "=^!+xₙ+=ᵈᵉᶠ" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\overset{!}{=}+\\underset{n}{x}+\\stackrel{def}{=}", got, ok, "=^!+xₙ+=ᵈᵉᶠ", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:340
	t.Run("renderLatex/renders indexed roots and additional accents and wrappers", func(t *testing.T) {
		if got, ok := RenderLatex("\\sqrt[2]{x}+\\sqrt[3]{x}+\\sqrt[4]{x}+\\sqrt[n]{x}+\\sqrt[k]{x+1}", RenderLatexOptions{Display: false}); ok != true || got != "√x+∛x+∜x+ⁿ√x+ᵏ√(x+1)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\sqrt[2]{x}+\\sqrt[3]{x}+\\sqrt[4]{x}+\\sqrt[n]{x}+\\sqrt[k]{x+1}", got, ok, "√x+∛x+∜x+ⁿ√x+ᵏ√(x+1)", true)
		}
		if got, ok := RenderLatex("\\acute{x}+\\grave{y}+\\widehat{xyz}+\\overrightarrow{AB}", RenderLatexOptions{Display: false}); ok != true || got != "x́+ỳ+widehat(xyz)+overrightarrow(AB)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\acute{x}+\\grave{y}+\\widehat{xyz}+\\overrightarrow{AB}", got, ok, "x́+ỳ+widehat(xyz)+overrightarrow(AB)", true)
		}
		if got, ok := RenderLatex("\\textnormal{hello}+\\mbox{world}+\\boldsymbol{x}+{\\rm roman}+{\\bf bold}+{\\it italic}+{\\sf sans}+{\\tt mono}+{\\cal calligraphic}+{\\sl slanted}", RenderLatexOptions{Display: false}); ok != true || got != "hello+world+x+roman+bold+italic+sans+mono+calligraphic+slanted" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\textnormal{hello}+\\mbox{world}+\\boldsymbol{x}+{\\rm roman}+{\\bf bold}+{\\it italic}+{\\sf sans}+{\\tt mono}+{\\cal calligraphic}+{\\sl slanted}", got, ok, "hello+world+x+roman+bold+italic+sans+mono+calligraphic+slanted", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:357
	t.Run("renderLatex/renders additional display environments", func(t *testing.T) {
		if got, ok := RenderLatex("\\begin{equation}\\begin{split}a&=b\\\\&=c\\end{split}\\end{equation}", RenderLatexOptions{Display: false}); ok != true || got != "a = b\n= c" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\begin{equation}\\begin{split}a&=b\\\\&=c\\end{split}\\end{equation}", got, ok, "a = b\n= c", true)
		}
		if got, ok := RenderLatex("\\begin{alignedat}{2}a&=b&\\quad c&=d\\\\e&=f&g&=h\\end{alignedat}", RenderLatexOptions{Display: false}); ok != true || got != "a = b c = d\ne = f g = h" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\begin{alignedat}{2}a&=b&\\quad c&=d\\\\e&=f&g&=h\\end{alignedat}", got, ok, "a = b c = d\ne = f g = h", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:368
	t.Run("renderLatex/uses natural case conditions and aligns matrix columns", func(t *testing.T) {
		if got, ok := RenderLatex("f(x)=\\begin{cases}a & x<0 \\\\ b & \\text{if }x=0 \\\\ c & \\text{otherwise}\\end{cases}", RenderLatexOptions{Display: false}); ok != true || got != "       ⎧ a if x < 0\nf(x) = ⎨ b if x = 0\n       ⎩ c otherwise" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "f(x)=\\begin{cases}a & x<0 \\\\ b & \\text{if }x=0 \\\\ c & \\text{otherwise}\\end{cases}", got, ok, "       ⎧ a if x < 0\nf(x) = ⎨ b if x = 0\n       ⎩ c otherwise", true)
		}
		if got, ok := RenderLatex("\\begin{pmatrix}1&200\\\\3000&4\\end{pmatrix}", RenderLatexOptions{Display: false}); ok != true || got != "⎛ 1    │ 200 ⎞\n⎝ 3000 │ 4   ⎠" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\begin{pmatrix}1&200\\\\3000&4\\end{pmatrix}", got, ok, "⎛ 1    │ 200 ⎞\n⎝ 3000 │ 4   ⎠", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:379
	t.Run("renderLatex/composes matrices with fractions and adjacent matrices", func(t *testing.T) {
		if got, ok := RenderLatex("R\\left(\\frac{\\pi}{4}\\right)\n=\n\\begin{pmatrix}\n\\frac{\\sqrt{2}}{2} & -\\frac{\\sqrt{2}}{2}\\\\\n\\frac{\\sqrt{2}}{2} & \\frac{\\sqrt{2}}{2}\n\\end{pmatrix}.", RenderLatexOptions{Display: true}); ok != true || got != "   π\nR( ─ ) = ⎛ (√2)/2 │ -(√2)/2 ⎞\n   4     ⎝ (√2)/2 │ (√2)/2  ⎠." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "R\\left(\\frac{\\pi}{4}\\right)\n=\n\\begin{pmatrix}\n\\frac{\\sqrt{2}}{2} & -\\frac{\\sqrt{2}}{2}\\\\\n\\frac{\\sqrt{2}}{2} & \\frac{\\sqrt{2}}{2}\n\\end{pmatrix}.", got, ok, "   π\nR( ─ ) = ⎛ (√2)/2 │ -(√2)/2 ⎞\n   4     ⎝ (√2)/2 │ (√2)/2  ⎠.", true)
		}
		if got, ok := RenderLatex("\\mathbf w\n=\nR\\left(\\frac{\\pi}{4}\\right)\n\\begin{pmatrix}1\\\\0\\end{pmatrix}\n=\n\\begin{pmatrix}\\frac{\\sqrt{2}}{2}\\\\\\frac{\\sqrt{2}}{2}\\end{pmatrix}.", RenderLatexOptions{Display: true}); ok != true || got != "       π\nw = R( ─ ) ⎛ 1 ⎞ = ⎛ (√2)/2 ⎞\n       4   ⎝ 0 ⎠   ⎝ (√2)/2 ⎠." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\mathbf w\n=\nR\\left(\\frac{\\pi}{4}\\right)\n\\begin{pmatrix}1\\\\0\\end{pmatrix}\n=\n\\begin{pmatrix}\\frac{\\sqrt{2}}{2}\\\\\\frac{\\sqrt{2}}{2}\\end{pmatrix}.", got, ok, "       π\nw = R( ─ ) ⎛ 1 ⎞ = ⎛ (√2)/2 ⎞\n       4   ⎝ 0 ⎠   ⎝ (√2)/2 ⎠.", true)
		}
		if got, ok := RenderLatex("A\\mathbf e_1=\\begin{pmatrix}\\pi\\\\0\\end{pmatrix},\\qquad A\\mathbf e_2=\\begin{pmatrix}0\\\\\\frac{1}{\\pi}\\end{pmatrix}.", RenderLatexOptions{Display: true}); ok != true || got != "Ae₁ = ⎛ π ⎞, Ae₂ = ⎛ 0   ⎞\n      ⎝ 0 ⎠        ⎝ 1/π ⎠." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "A\\mathbf e_1=\\begin{pmatrix}\\pi\\\\0\\end{pmatrix},\\qquad A\\mathbf e_2=\\begin{pmatrix}0\\\\\\frac{1}{\\pi}\\end{pmatrix}.", got, ok, "Ae₁ = ⎛ π ⎞, Ae₂ = ⎛ 0   ⎞\n      ⎝ 0 ⎠        ⎝ 1/π ⎠.", true)
		}
		if got, ok := RenderLatex("\\sum_{i=0}^n x_i=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}.", RenderLatexOptions{Display: true}); ok != true || got != " n\n ∑  xᵢ = ⎛ a │ b ⎞\ni=0      ⎝ c │ d ⎠." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\sum_{i=0}^n x_i=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}.", got, ok, " n\n ∑  xᵢ = ⎛ a │ b ⎞\ni=0      ⎝ c │ d ⎠.", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:417
	t.Run("renderLatex/normalizes relation, multiplication, and named-operator spacing", func(t *testing.T) {
		if got, ok := RenderLatex("x=y", RenderLatexOptions{Display: false}); ok != true || got != "x = y" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x=y", got, ok, "x = y", true)
		}
		if got, ok := RenderLatex("x =y", RenderLatexOptions{Display: false}); ok != true || got != "x = y" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x =y", got, ok, "x = y", true)
		}
		if got, ok := RenderLatex("x=\ny", RenderLatexOptions{Display: false}); ok != true || got != "x = y" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x=\ny", got, ok, "x = y", true)
		}
		if got, ok := RenderLatex("x\n=\ny", RenderLatexOptions{Display: false}); ok != true || got != "x = y" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x\n=\ny", got, ok, "x = y", true)
		}
		if got, ok := RenderLatex("x_{i=0}", RenderLatexOptions{Display: false}); ok != true || got != "xᵢ₌₀" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x_{i=0}", got, ok, "xᵢ₌₀", true)
		}
		if got, ok := RenderLatex("x\\neq0", RenderLatexOptions{Display: false}); ok != true || got != "x ≠ 0" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x\\neq0", got, ok, "x ≠ 0", true)
		}
		if got, ok := RenderLatex("A\\to B", RenderLatexOptions{Display: false}); ok != true || got != "A → B" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "A\\to B", got, ok, "A → B", true)
		}
		if got, ok := RenderLatex("\\pi\\cdot\\frac{1}{\\pi}", RenderLatexOptions{Display: false}); ok != true || got != "π · 1/π" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\pi\\cdot\\frac{1}{\\pi}", got, ok, "π · 1/π", true)
		}
		if got, ok := RenderLatex("\\sin\\theta", RenderLatexOptions{Display: false}); ok != true || got != "sin θ" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\sin\\theta", got, ok, "sin θ", true)
		}
		if got, ok := RenderLatex("\\sin^2 x", RenderLatexOptions{Display: false}); ok != true || got != "sin² x" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\sin^2 x", got, ok, "sin² x", true)
		}
		if got, ok := RenderLatex("-\\sin\\theta", RenderLatexOptions{Display: false}); ok != true || got != "-sin θ" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "-\\sin\\theta", got, ok, "-sin θ", true)
		}
		if got, ok := RenderLatex("i\\sin\\theta", RenderLatexOptions{Display: false}); ok != true || got != "i sin θ" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "i\\sin\\theta", got, ok, "i sin θ", true)
		}
		if got, ok := RenderLatex("\\det(A)", RenderLatexOptions{Display: false}); ok != true || got != "det(A)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\det(A)", got, ok, "det(A)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:432
	t.Run("renderLatex/treats a backslash followed by a line ending as control space", func(t *testing.T) {
		if got, ok := RenderLatex("\\boxed{\n(1,1,1),\\ (1,1,2),\\ (1,2,5),\\ (1,5,13),\\ (2,5,29),\\\n(1,13,34),\\ (1,34,89)\n}.", RenderLatexOptions{Display: true}); ok != true || got != "[(1,1,1), (1,1,2), (1,2,5), (1,5,13), (2,5,29), (1,13,34), (1,34,89)]." {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\boxed{\n(1,1,1),\\ (1,1,2),\\ (1,2,5),\\ (1,5,13),\\ (2,5,29),\\\n(1,13,34),\\ (1,34,89)\n}.", got, ok, "[(1,1,1), (1,1,2), (1,2,5), (1,5,13), (2,5,29), (1,13,34), (1,34,89)].", true)
		}
		if got, ok := RenderLatex("a\\\r\nb", RenderLatexOptions{Display: false}); ok != true || got != "a b" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "a\\\r\nb", got, ok, "a b", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:444
	t.Run("renderLatex/stacks operator limits in display mode", func(t *testing.T) {
		if got, ok := RenderLatex("\\sum_{i=0}^n x_i", RenderLatexOptions{Display: true}); ok != true || got != " n\n ∑  xᵢ\ni=0" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\sum_{i=0}^n x_i", got, ok, " n\n ∑  xᵢ\ni=0", true)
		}
		if got, ok := RenderLatex("\\min_{x\\in X} f(x)", RenderLatexOptions{Display: true}); ok != true || got != "min f(x)\nx∈X" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\min_{x\\in X} f(x)", got, ok, "min f(x)\nx∈X", true)
		}
		if got, ok := RenderLatex("\\operatorname*{arg\\,max}_{x\\in X} f(x)", RenderLatexOptions{Display: true}); ok != true || got != "arg max f(x)\n  x∈X" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\operatorname*{arg\\,max}_{x\\in X} f(x)", got, ok, "arg max f(x)\n  x∈X", true)
		}
		if got, ok := RenderLatex("\\int\\nolimits_0^1 f(x)\\,dx", RenderLatexOptions{Display: true}); ok != true || got != "∫₀¹ f(x) dx" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\int\\nolimits_0^1 f(x)\\,dx", got, ok, "∫₀¹ f(x) dx", true)
		}
		if got, ok := RenderLatex("\\int\\limits_0^1 f(x)\\,dx", RenderLatexOptions{Display: true}); ok != true || got != "1\n∫ f(x) dx\n0" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\int\\limits_0^1 f(x)\\,dx", got, ok, "1\n∫ f(x) dx\n0", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:457
	t.Run("renderLatex/centers even case rows around a middle brace", func(t *testing.T) {
		if got, ok := RenderLatex("f(x) = \\begin{cases} x^{2} & x \\geq 0 \\\\ -x & x < 0 \\end{cases}", RenderLatexOptions{Display: false}); ok != true || got != "       ⎧ x² if x ≥ 0\nf(x) = ⎨\n       ⎩ -x if x < 0" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "f(x) = \\begin{cases} x^{2} & x \\geq 0 \\\\ -x & x < 0 \\end{cases}", got, ok, "       ⎧ x² if x ≥ 0\nf(x) = ⎨\n       ⎩ -x if x < 0", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:464
	t.Run("renderLatex/stacks fractions in display mode", func(t *testing.T) {
		if got, ok := RenderLatex("x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}", RenderLatexOptions{Display: true}); ok != true || got != "    -b±√(b²-4ac)\nx = ────────────\n         2a" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}", got, ok, "    -b±√(b²-4ac)\nx = ────────────\n         2a", true)
		}
		if got, ok := RenderLatex("\\frac{x^2+1}{x-1}", RenderLatexOptions{Display: true}); ok != true || got != "x²+1\n────\nx-1" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\frac{x^2+1}{x-1}", got, ok, "x²+1\n────\nx-1", true)
		}
		if got, ok := RenderLatex("\\frac{1}\n{2}", RenderLatexOptions{Display: true}); ok != true || got != "1\n─\n2" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\frac{1}\n{2}", got, ok, "1\n─\n2", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:475
	t.Run("renderLatex/keeps nested display fractions linear", func(t *testing.T) {
		if got, ok := RenderLatex("\\frac{\\frac{x^2+1}{x-1}-\\frac{2x}{x+1}}{\\frac{x}{x^2-1}}", RenderLatexOptions{Display: true}); ok != true || got != "(x²+1)/(x-1)-2x/(x+1)\n─────────────────────\n      x/(x²-1)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\frac{\\frac{x^2+1}{x-1}-\\frac{2x}{x+1}}{\\frac{x}{x^2-1}}", got, ok, "(x²+1)/(x-1)-2x/(x+1)\n─────────────────────\n      x/(x²-1)", true)
		}
		if got, ok := RenderLatex("\\lim_{x\\to 0}\\frac{\\frac{\\sin x}{x}-1}{\\frac{e^x-1}{x}-1}=0", RenderLatexOptions{Display: true}); ok != true || got != "     (sin x)/x-1\nlim  ─────────── = 0\nx→0  (eˣ-1)/x-1" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\lim_{x\\to 0}\\frac{\\frac{\\sin x}{x}-1}{\\frac{e^x-1}{x}-1}=0", got, ok, "     (sin x)/x-1\nlim  ─────────── = 0\nx→0  (eˣ-1)/x-1", true)
		}
		if got, ok := RenderLatex("\\frac{1+\\frac{1}{1+\\frac{1}{x}}}{1-\\frac{1}{1-\\frac{1}{x}}}", RenderLatexOptions{Display: true}); ok != true || got != "1+1/(1+1/x)\n───────────\n1-1/(1-1/x)" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\frac{1+\\frac{1}{1+\\frac{1}{x}}}{1-\\frac{1}{1-\\frac{1}{x}}}", got, ok, "1+1/(1+1/x)\n───────────\n1-1/(1-1/x)", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:495
	t.Run("renderLatex/lays out unsupported and nested scripts while keeping script fractions linear", func(t *testing.T) {
		if got, ok := RenderLatex("\\partial_tU_2(t,0)=Aj_*(1-t)^{-A-1}.\\qquad x^{n^2}+x_{i_j}", RenderLatexOptions{Display: true}); ok != true || got != "                            2\n                    -A-1   n\n∂ₜU₂(t,0) = Aj (1-t)    . x  +x\n              *                i\n                                j" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\partial_tU_2(t,0)=Aj_*(1-t)^{-A-1}.\\qquad x^{n^2}+x_{i_j}", got, ok, "                            2\n                    -A-1   n\n∂ₜU₂(t,0) = Aj (1-t)    . x  +x\n              *                i\n                                j", true)
		}
		if got, ok := RenderLatex("e^{\\frac{1}{2}}+\\tfrac{1}{2}", RenderLatexOptions{Display: true}); ok != true || got != "e^(1/2)+1/2" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "e^{\\frac{1}{2}}+\\tfrac{1}{2}", got, ok, "e^(1/2)+1/2", true)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:505
	t.Run("renderLatex/returns undefined for unsupported commands", func(t *testing.T) {
		if got, ok := RenderLatex("x + \\unknown{y}", RenderLatexOptions{Display: false}); ok != false || got != "" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x + \\unknown{y}", got, ok, "", false)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/latex.test.ts:509
	t.Run("renderLatex/returns undefined for malformed groups and environments", func(t *testing.T) {
		if got, ok := RenderLatex("\\frac{1}{x", RenderLatexOptions{Display: false}); ok != false || got != "" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\frac{1}{x", got, ok, "", false)
		}
		if got, ok := RenderLatex("x}", RenderLatexOptions{Display: false}); ok != false || got != "" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x}", got, ok, "", false)
		}
		if got, ok := RenderLatex("\\begin{matrix}1 & 2", RenderLatexOptions{Display: false}); ok != false || got != "" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "\\begin{matrix}1 & 2", got, ok, "", false)
		}
		if got, ok := RenderLatex("x\\", RenderLatexOptions{Display: false}); ok != false || got != "" {
			t.Errorf("RenderLatex(%q) = (%q, %v), want (%q, %v)", "x\\", got, ok, "", false)
		}
	})
}
