// Code generated by test/parity/testdata/markdown-upstream-tests.mjs; DO NOT EDIT.
package tui

import (
	"github.com/MichaelKinsy/PiG/tui/widthx"
	"slices"
	"strings"
	"testing"
)

func TestUpstreamMarkdown(t *testing.T) {
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:31
	t.Run("caches transformed Markdown by source and available width", func(t *testing.T) {
		mdCaseSetup(t)
		testMDTransformCache(t)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:69
	t.Run("should render simple nested list", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("- Item 1\n  - Nested 1.1\n  - Nested 1.2\n- Item 2", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		mdAssert(t, (mdLen(lines) > 0), "lines.length > 0")
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "- Item 1") }), "plainLines.some((line) => line.includes(\"- Item 1\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "    - Nested 1.1") }), "plainLines.some((line) => line.includes(\"    - Nested 1.1\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "    - Nested 1.2") }), "plainLines.some((line) => line.includes(\"    - Nested 1.2\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "- Item 2") }), "plainLines.some((line) => line.includes(\"- Item 2\"))")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:95
	t.Run("should render deeply nested list", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("- Level 1\n  - Level 2\n    - Level 3\n      - Level 4", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "- Level 1") }), "plainLines.some((line) => line.includes(\"- Level 1\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "    - Level 2") }), "plainLines.some((line) => line.includes(\"    - Level 2\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "        - Level 3") }), "plainLines.some((line) => line.includes(\"        - Level 3\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "            - Level 4") }), "plainLines.some((line) => line.includes(\"            - Level 4\"))")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:116
	t.Run("should render ordered nested list", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("1. First\n   1. Nested first\n   2. Nested second\n2. Second", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "1. First") }), "plainLines.some((line) => line.includes(\"1. First\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "    1. Nested first") }), "plainLines.some((line) => line.includes(\"    1. Nested first\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "    2. Nested second") }), "plainLines.some((line) => line.includes(\"    2. Nested second\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "2. Second") }), "plainLines.some((line) => line.includes(\"2. Second\"))")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:136
	t.Run("should normalize ordered list markers by default", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("1. alpha\n1. beta\n1. gamma", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"1. alpha", "2. beta", "3. gamma"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:144
	t.Run("should preserve source list markers when configured", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("  4. forth\n  3. third\n\n10) ten\n7) seven\n\n+ plus\n* star\n- minus\n+", 0, 0, mdUpstreamTheme(), nil, &MarkdownOptions{PreserveOrderedListMarkers: true})
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"4. forth", "3. third", "", "10) ten", "7) seven", "", "+ plus", "* star", "- minus", "+"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:172
	t.Run("should render mixed ordered and unordered nested lists", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("1. Ordered item\n   - Unordered nested\n   - Another nested\n2. Second ordered\n   - More nested", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "1. Ordered item") }), "plainLines.some((line) => line.includes(\"1. Ordered item\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "    - Unordered nested") }), "plainLines.some((line) => line.includes(\"    - Unordered nested\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "2. Second ordered") }), "plainLines.some((line) => line.includes(\"2. Second ordered\"))")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:192
	t.Run("should render blank lines between loose list items", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("1. Lorem ipsum dolor sit amet.\n\n   Ut enim ad minim veniam.\n\n2. Duis aute irure dolor.\n\n   Excepteur sint occaecat cupidatat.\n\n3. Beep boop", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"1. Lorem ipsum dolor sit amet.", "", "   Ut enim ad minim veniam.", "", "2. Duis aute irure dolor.", "", "   Excepteur sint occaecat cupidatat.", "", "3. Beep boop"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:223
	t.Run("should render task list markers", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("- [ ] beep\n- [x] boop", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"- [ ] beep", "- [x] boop"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:231
	t.Run("should maintain numbering when code blocks are not indented (LLM output)", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("1. First item\n\n```typescript\n// code block\n```\n\n2. Second item\n\n```typescript\n// another code block\n```\n\n3. Third item", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrim(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		numberedLines := mdFilter(plainLines, func(line string) bool { return mdMatch("^\\d+\\.", line) })
		mdEqual(t, mdLen(numberedLines), 3)
		mdAssert(t, strings.HasPrefix(numberedLines[0], "1."), "numberedLines[0].startsWith(\"1.\")")
		mdAssert(t, strings.HasPrefix(numberedLines[1], "2."), "numberedLines[1].startsWith(\"2.\")")
		mdAssert(t, strings.HasPrefix(numberedLines[2], "3."), "numberedLines[2].startsWith(\"3.\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:268
	t.Run("should indent wrapped unordered list lines", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("- alpha beta gamma delta epsilon", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(20), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"- alpha beta gamma", "  delta epsilon"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:276
	t.Run("should indent wrapped ordered list lines", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("1. alpha beta gamma delta epsilon", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(20), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"1. alpha beta gamma", "   delta epsilon"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:284
	t.Run("should indent wrapped ordered list lines with multi-digit markers", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("10. alpha beta gamma delta epsilon", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(21), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"10. alpha beta gamma", "    delta epsilon"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:292
	t.Run("should indent wrapped nested list lines", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("- parent\n  - alpha beta gamma delta epsilon", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(24), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"- parent", "    - alpha beta gamma", "      delta epsilon"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:300
	t.Run("should indent wrapped nested list lines under ordered parents", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("1. parent\n   - alpha beta gamma delta epsilon", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(24), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"1. parent", "    - alpha beta gamma", "      delta epsilon"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:308
	t.Run("should render and wrap blockquotes inside list items", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("- > alpha beta gamma delta epsilon zeta", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(24), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"- │ alpha beta gamma", "  │ delta epsilon zeta"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:316
	t.Run("should render and wrap code blocks inside list items", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("- ```ts\n  alpha beta gamma delta epsilon zeta\n  ```", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(24), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"- ```ts", "    alpha beta gamma", "  delta epsilon zeta", "  ```"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:331
	t.Run("should render simple table", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| Name | Age |\n| --- | --- |\n| Alice | 30 |\n| Bob | 25 |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Name") }), "plainLines.some((line) => line.includes(\"Name\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Age") }), "plainLines.some((line) => line.includes(\"Age\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Alice") }), "plainLines.some((line) => line.includes(\"Alice\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Bob") }), "plainLines.some((line) => line.includes(\"Bob\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "│") }), "plainLines.some((line) => line.includes(\"│\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "─") }), "plainLines.some((line) => line.includes(\"─\"))")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:355
	t.Run("should render row dividers between data rows", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| Name | Age |\n| --- | --- |\n| Alice | 30 |\n| Bob | 25 |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		dividerLines := mdFilter(plainLines, func(line string) bool { return strings.Contains(line, "┼") })
		mdEqual(t, mdLen(dividerLines), 2)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:373
	t.Run("should keep column width at least the longest word", func(t *testing.T) {
		mdCaseSetup(t)
		longestWord := "superlongword"
		markdown := NewMarkdownWithOptions(("| Column One | Column Two |\n| --- | --- |\n| " + longestWord + " short | otherword |\n| small | tiny |"), 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(32)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		dataLine := mdFind(plainLines, func(line string) bool { return strings.Contains(line, longestWord) })
		mdAssert(t, dataLine, "dataLine")
		segments := mdSlice(strings.Split(dataLine, "│"), 1, -1)
		firstSegment := mdAt(segments, 0)
		mdAssert(t, firstSegment, "firstSegment")
		firstColumnWidth := (mdLen(firstSegment) - 2)
		mdAssert(t, (firstColumnWidth >= mdLen(longestWord)), "firstColumnWidth >= longestWord.length")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:401
	t.Run("should render table with alignment", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| Left | Center | Right |\n| :--- | :---: | ---: |\n| A | B | C |\n| Long text | Middle | End |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Left") }), "plainLines.some((line) => line.includes(\"Left\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Center") }), "plainLines.some((line) => line.includes(\"Center\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Right") }), "plainLines.some((line) => line.includes(\"Right\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Long text") }), "plainLines.some((line) => line.includes(\"Long text\"))")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:423
	t.Run("should handle tables with varying column widths", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| Short | Very long column header |\n| --- | --- |\n| A | This is a much longer cell content |\n| B | Short |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		mdAssert(t, (mdLen(lines) > 0), "lines.length > 0")
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Very long column header") }), "plainLines.some((line) => line.includes(\"Very long column header\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "This is a much longer cell content") }), "plainLines.some((line) => line.includes(\"This is a much longer cell content\"))")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:444
	t.Run("should wrap table cells when table exceeds available width", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| Command | Description | Example |\n| --- | --- | --- |\n| npm install | Install all dependencies | npm install |\n| npm run build | Build the project | npm run build |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(50)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		for _, line := range plainLines {
			mdAssert(t, (mdLen(line) <= 50), "line.length <= 50")
		}
		allText := strings.Join(plainLines, " ")
		mdAssert(t, strings.Contains(allText, "Command"), "allText.includes(\"Command\")")
		mdAssert(t, strings.Contains(allText, "Description"), "allText.includes(\"Description\")")
		mdAssert(t, strings.Contains(allText, "npm install"), "allText.includes(\"npm install\")")
		mdAssert(t, strings.Contains(allText, "Install"), "allText.includes(\"Install\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:472
	t.Run("should not leak wrapped link styles into table borders or plain cells", func(t *testing.T) {
		mdCaseSetup(t)
		testMDTableLinkStyles(t)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:523
	t.Run("should restore the enclosing style after a wrapped table link", func(t *testing.T) {
		mdCaseSetup(t)
		testMDQuoteTableStyles(t)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:571
	t.Run("should wrap long cell content to multiple lines", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| Header |\n| --- |\n| This is a very long cell content that should wrap |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(25)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		dataRows := mdFilter(plainLines, func(line string) bool { return (strings.HasPrefix(line, "│") && !strings.Contains(line, "─")) })
		mdAssert(t, (mdLen(dataRows) > 2), "dataRows.length > 2")
		allText := strings.Join(plainLines, " ")
		mdAssert(t, strings.Contains(allText, "very long"), "allText.includes(\"very long\")")
		mdAssert(t, strings.Contains(allText, "cell content"), "allText.includes(\"cell content\")")
		mdAssert(t, strings.Contains(allText, "should wrap"), "allText.includes(\"should wrap\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:596
	t.Run("should wrap long unbroken tokens inside table cells (not only at line start)", func(t *testing.T) {
		mdCaseSetup(t)
		SetCapabilities(TerminalCapabilities{TrueColor: false, Hyperlinks: false})
		url := "https://example.com/this/is/a/very/long/url/that/should/wrap"
		markdown := NewMarkdownWithOptions(("| Value |\n| --- |\n| prefix " + url + " |"), 0, 0, mdUpstreamTheme(), nil, nil)
		width := 30
		lines := markdown.Render(width)
		ResetCapabilitiesCache()
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		for _, line := range plainLines {
			mdAssert(t, (mdLen(line) <= width), "line.length <= width")
		}
		tableLines := mdFilter(plainLines, func(line string) bool { return strings.HasPrefix(line, "│") })
		mdAssert(t, (mdLen(tableLines) > 0), "tableLines.length > 0")
		for _, line := range tableLines {
			borderCount := (mdLen(strings.Split(line, "│")) - 1)
			mdEqual(t, borderCount, 2)
		}
		extracted := mdReplace(strings.Join(plainLines, ""), "[│├┤─\\s]", "")
		mdAssert(t, strings.Contains(extracted, "prefix"), "extracted.includes(\"prefix\")")
		mdAssert(t, strings.Contains(extracted, url), "extracted.includes(url)")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:633
	t.Run("should wrap styled inline code inside table cells without breaking borders", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| Code |\n| --- |\n| `averyveryveryverylongidentifier` |", 0, 0, mdUpstreamTheme(), nil, nil)
		width := 20
		lines := markdown.Render(width)
		joinedOutput := strings.Join(lines, "\n")
		mdAssert(t, strings.Contains(joinedOutput, "\u001b[33m"), "joinedOutput.includes(\"\\x1b[33m\")")
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		for _, line := range plainLines {
			mdAssert(t, (mdLen(line) <= width), "line.length <= width")
		}
		tableLines := mdFilter(plainLines, func(line string) bool { return strings.HasPrefix(line, "│") })
		for _, line := range tableLines {
			borderCount := (mdLen(strings.Split(line, "│")) - 1)
			mdEqual(t, borderCount, 2)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:660
	t.Run("should handle extremely narrow width gracefully", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| A | B | C |\n| --- | --- | --- |\n| 1 | 2 | 3 |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(15)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		mdAssert(t, (mdLen(lines) > 0), "lines.length > 0")
		for _, line := range plainLines {
			mdAssert(t, (mdLen(line) <= 15), "line.length <= 15")
		}
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:683
	t.Run("should render table correctly when it fits naturally", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| A | B |\n| --- | --- |\n| 1 | 2 |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		headerLine := mdFind(plainLines, func(line string) bool { return (strings.Contains(line, "A") && strings.Contains(line, "B")) })
		mdAssert(t, headerLine, "headerLine")
		mdAssert(t, strings.Contains(headerLine, "│"), "headerLine?.includes(\"│\")")
		separatorLine := mdFind(plainLines, func(line string) bool { return (strings.Contains(line, "├") && strings.Contains(line, "┼")) })
		mdAssert(t, separatorLine, "separatorLine")
		dataLine := mdFind(plainLines, func(line string) bool { return (strings.Contains(line, "1") && strings.Contains(line, "2")) })
		mdAssert(t, dataLine, "dataLine")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:709
	t.Run("should respect paddingX when calculating table width", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| Column One | Column Two |\n| --- | --- |\n| Data 1 | Data 2 |", 2, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(40)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		for _, line := range plainLines {
			mdAssert(t, (mdLen(line) <= 40), "line.length <= 40")
		}
		tableRow := mdFind(plainLines, func(line string) bool { return strings.Contains(line, "│") })
		mdAssert(t, strings.HasPrefix(tableRow, "  "), "tableRow?.startsWith(\"  \")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:733
	t.Run("should not add a trailing blank line when table is the last rendered block", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("| Name |\n| --- |\n| Alice |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		mdNotEqual(t, mdAt(plainLines, -1), "")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:755
	t.Run("should render lists and tables together", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("# Test Document\n\n- Item 1\n  - Nested item\n- Item 2\n\n| Col1 | Col2 |\n| --- | --- |\n| A | B |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Test Document") }), "plainLines.some((line) => line.includes(\"Test Document\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "- Item 1") }), "plainLines.some((line) => line.includes(\"- Item 1\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "    - Nested item") }), "plainLines.some((line) => line.includes(\"    - Nested item\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "Col1") }), "plainLines.some((line) => line.includes(\"Col1\"))")
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.Contains(line, "│") }), "plainLines.some((line) => line.includes(\"│\"))")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:786
	t.Run("renders inline dollar and parenthesis delimiters", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("A map $\\mathbb{C}^3 \\to \\mathbb{C}^3$, $xy$, $x-y$, $-x$, $\\frac{1}{2}$, $\\rightarrow$, and \\(s \\to \\infty\\).", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"A map ℂ³ → ℂ³, xy, x-y, -x, 1/2, →, and s → ∞."})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:799
	t.Run("renders display dollar delimiters without Markdown escape corruption", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("Before\n\n$$\\{3x+2y,\\; x \\in \\{0, \\pm 1\\}\\}$$\n\nafter", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"Before", "", "{3x+2y, x ∈ {0, ± 1}}", "", "after"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:816
	t.Run("renders display bracket delimiters", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("Before\n\n\\[\nE \\approx \\frac{0.1\\ \\text{lux}}{100\\ \\text{lm/W}}\n\\]\n\nafter", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"Before", "", "    0.1 lux", "E ≈ ────────", "    100 lm/W", "", "after"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:835
	t.Run("aligns matrix rows with the opening delimiter", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("Consider the matrix\n\n\\[\nA=\n\\begin{pmatrix}\n\\pi & 0\\\\\n0 & \\frac{1}{\\pi}\n\\end{pmatrix}.\n\\]", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"Consider the matrix", "", "A = ⎛ π │ 0   ⎞", "    ⎝ 0 │ 1/π ⎠."})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:856
	t.Run("renders lower limits beneath display operators", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("\\[\n\\lim_{x\\to 0}\\frac{\\frac{\\sin x}{x}-1}{\\frac{e^x-1}{x}-1}=0\n\\]", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"     (sin x)/x-1", "lim  ─────────── = 0", "x→0  (eˣ-1)/x-1"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:871
	t.Run("renders math inside lists and tables", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("- Formula: $F_1 = u^2$\n\n| Value |\n| --- |\n| $\\mathbb{C}^3$ |", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		output := strings.Join(lines, "\n")
		mdAssert(t, strings.Contains(output, "- Formula: F₁ = u²"), "output.includes(\"- Formula: F₁ = u²\")")
		mdAssert(t, strings.Contains(output, "│ ℂ³"), "output.includes(\"│ ℂ³\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:890
	t.Run("does not treat currency, shell variables, or code spans as math", func(t *testing.T) {
		mdCaseSetup(t)
		source := ("Costs $5 and $10 or $8k–$12k; use `$x$`, $HOME, and $" + "{PATH}.")
		markdown := NewMarkdownWithOptions(source, 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{("Costs $5 and $10 or $8k–$12k; use $x$, $HOME, and $" + "{PATH}.")})
		shellVariables := "Paths: $HOME/$USER and $XDG_CONFIG_HOME/$APP_CONFIG"
		shellLines := mdMap(NewMarkdownWithOptions(shellVariables, 0, 0, mdUpstreamTheme(), nil, nil).Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, shellLines, []string{shellVariables})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:905
	t.Run("preserves unsupported and incomplete LaTeX exactly", func(t *testing.T) {
		mdCaseSetup(t)
		cases := []string{"Unknown $x + \\unknown{y}$ after", "Streaming $\\mathbb{C}^3"}
		for _, source := range cases {
			markdown := NewMarkdownWithOptions(source, 0, 0, mdUpstreamTheme(), nil, nil)
			lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
			mdEqual(t, lines, []string{source})
		}
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:915
	t.Run("preserves incomplete backslash delimiters while streaming", func(t *testing.T) {
		mdCaseSetup(t)
		inline := NewMarkdownWithOptions("Map \\(\\mathbb{C}^3", 0, 0, mdUpstreamTheme(), nil, nil)
		mdEqual(t, mdMap(inline.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) }), []string{"Map \\(\\mathbb{C}^3"})
		display := NewMarkdownWithOptions("\\[\nx^2", 0, 0, mdUpstreamTheme(), nil, nil)
		mdEqual(t, mdMap(display.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) }), []string{"\\[", "x^2"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:929
	t.Run("does not render LaTeX inside escaped delimiters or code fences", func(t *testing.T) {
		mdCaseSetup(t)
		source := strings.Join([]string{"Escaped \\$x-y\\$.", "", "```text", "$\\mathbb{C}^3$", "```"}, "\n")
		markdown := NewMarkdownWithOptions(source, 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"Escaped $x-y$.", "", "```text", "  $\\mathbb{C}^3$", "```"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:937
	t.Run("allows LaTeX rendering to be disabled", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("$$\n\\widetilde Y_{sf}\n=\n(1-w_{sf})\\mu_{sf}^{\\mathrm{MAR}}\n$$\n\nInline \\(A_{sf}\\)", 0, 0, mdUpstreamTheme(), nil, &MarkdownOptions{RenderLatex: new(false)})
		mdEqual(t, mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) }), []string{"$$", "\\widetilde Y_{sf}", "=", "(1-w_{sf})\\mu_{sf}^{\\mathrm{MAR}}", "$$", "", "Inline \\(A_{sf}\\)"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:969
	t.Run("switches from raw to rendered math when a streamed delimiter closes", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("Map $\\mathbb{C}^3", 0, 0, mdUpstreamTheme(), nil, nil)
		mdEqual(t, mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) }), []string{"Map $\\mathbb{C}^3"})
		markdown.SetText("Map $\\mathbb{C}^3$")
		mdEqual(t, mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) }), []string{"Map ℂ³"})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:986
	t.Run("should normalize escaped punctuation by default", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("\"\\\"", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"\"\""})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:994
	t.Run("should preserve source backslash escapes when configured", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("\"\\\"", 0, 0, mdUpstreamTheme(), nil, &MarkdownOptions{PreserveBackslashEscapes: true})
		lines := mdMap(markdown.Render(80), func(line string) string { return widthx.JSTrimEnd(mdStripSGR(line)) })
		mdEqual(t, lines, []string{"\"\\\""})
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1006
	t.Run("should preserve gray italic styling after inline code", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("This is thinking with `inline code` and more text after", 1, 0, mdUpstreamTheme(), &DefaultTextStyle{Color: mdChalk("gray"), Italic: true}, nil)
		lines := markdown.Render(80)
		joinedOutput := strings.Join(lines, "\n")
		mdAssert(t, strings.Contains(joinedOutput, "inline code"), "joinedOutput.includes(\"inline code\")")
		mdAssert(t, strings.Contains(joinedOutput, "\u001b[90m"), "joinedOutput.includes(\"\\x1b[90m\")")
		mdAssert(t, strings.Contains(joinedOutput, "\u001b[3m"), "joinedOutput.includes(\"\\x1b[3m\")")
		hasCodeColor := strings.Contains(joinedOutput, "\u001b[33m")
		mdAssert(t, hasCodeColor, "hasCodeColor")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1034
	t.Run("should preserve gray italic styling after bold text", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("This is thinking with **bold text** and more after", 1, 0, mdUpstreamTheme(), &DefaultTextStyle{Color: mdChalk("gray"), Italic: true}, nil)
		lines := markdown.Render(80)
		joinedOutput := strings.Join(lines, "\n")
		mdAssert(t, strings.Contains(joinedOutput, "bold text"), "joinedOutput.includes(\"bold text\")")
		mdAssert(t, strings.Contains(joinedOutput, "\u001b[90m"), "joinedOutput.includes(\"\\x1b[90m\")")
		mdAssert(t, strings.Contains(joinedOutput, "\u001b[3m"), "joinedOutput.includes(\"\\x1b[3m\")")
		mdAssert(t, strings.Contains(joinedOutput, "\u001b[1m"), "joinedOutput.includes(\"\\x1b[1m\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1060
	t.Run("should not leak styles into following lines when rendered in TUI", func(t *testing.T) {
		mdCaseSetup(t)
		testMDStyledInputLine(t)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1100
	t.Run("should have only one blank line between code block and following paragraph", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("hello world\n\n```js\nconst hello = \"world\";\n```\n\nagain, hello world", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		closingBackticksIndex := slices.Index(plainLines, "```")
		mdAssert(t, (closingBackticksIndex != -1), "closingBackticksIndex !== -1")
		afterBackticks := mdSlice(plainLines, (closingBackticksIndex + 1))
		emptyLineCount := slices.IndexFunc(afterBackticks, func(line string) bool { return (line != "") })
		mdEqual(t, emptyLineCount, 1)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1130
	t.Run("should normalize paragraph and code block spacing to one blank line", func(t *testing.T) {
		mdCaseSetup(t)
		cases := []string{"hello this is text\n```\ncode block\n```\nmore text", "hello this is text\n\n```\ncode block\n```\n\nmore text"}
		expectedLines := []string{"hello this is text", "", "```", "  code block", "```", "", "more text"}
		for _, text := range cases {
			markdown := NewMarkdownWithOptions(text, 0, 0, mdUpstreamTheme(), nil, nil)
			lines := markdown.Render(80)
			plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
			mdEqual(t, plainLines, expectedLines)
		}
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1160
	t.Run("should not add a trailing blank line when code block is the last rendered block", func(t *testing.T) {
		mdCaseSetup(t)
		cases := []string{"```js\nconst hello = 'world';\n```", "hello world\n\n```js\nconst hello = 'world';\n```"}
		for _, text := range cases {
			markdown := NewMarkdownWithOptions(text, 0, 0, mdUpstreamTheme(), nil, nil)
			lines := markdown.Render(80)
			plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
			mdNotEqual(t, mdAt(plainLines, -1), "")
		}
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1178
	t.Run("should have only one blank line between divider and following paragraph", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("hello world\n\n---\n\nagain, hello world", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		dividerIndex := slices.IndexFunc(plainLines, func(line string) bool { return strings.Contains(line, "─") })
		mdAssert(t, (dividerIndex != -1), "dividerIndex !== -1")
		afterDivider := mdSlice(plainLines, (dividerIndex + 1))
		emptyLineCount := slices.IndexFunc(afterDivider, func(line string) bool { return (line != "") })
		mdEqual(t, emptyLineCount, 1)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1206
	t.Run("should not add a trailing blank line when divider is the last rendered block", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("---", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		mdNotEqual(t, mdAt(plainLines, -1), "")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1220
	t.Run("should have only one blank line between heading and following paragraph", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("# Hello\n\nThis is a paragraph", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		headingIndex := slices.IndexFunc(plainLines, func(line string) bool { return strings.Contains(line, "Hello") })
		mdAssert(t, (headingIndex != -1), "headingIndex !== -1")
		afterHeading := mdSlice(plainLines, (headingIndex + 1))
		emptyLineCount := slices.IndexFunc(afterHeading, func(line string) bool { return (line != "") })
		mdEqual(t, emptyLineCount, 1)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1246
	t.Run("should not add a trailing blank line when heading is the last rendered block", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("# Hello", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		mdNotEqual(t, mdAt(plainLines, -1), "")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1260
	t.Run("should have only one blank line between blockquote and following paragraph", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("hello world\n\n> This is a quote\n\nagain, hello world", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		quoteIndex := slices.IndexFunc(plainLines, func(line string) bool { return strings.Contains(line, "This is a quote") })
		mdAssert(t, (quoteIndex != -1), "quoteIndex !== -1")
		afterQuote := mdSlice(plainLines, (quoteIndex + 1))
		emptyLineCount := slices.IndexFunc(afterQuote, func(line string) bool { return (line != "") })
		mdEqual(t, emptyLineCount, 1)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1288
	t.Run("should not add a trailing blank line when blockquote is the last rendered block", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("> This is a quote", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		mdNotEqual(t, mdAt(plainLines, -1), "")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1302
	t.Run("should apply consistent styling to all lines in lazy continuation blockquote", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions(">Foo\nbar", 0, 0, mdUpstreamTheme(), &DefaultTextStyle{Color: mdChalk("magenta")}, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		quotedLines := mdFilter(plainLines, func(line string) bool { return strings.HasPrefix(line, "│ ") })
		mdEqual(t, mdLen(quotedLines), 2)
		fooLine := mdFind(lines, func(line string) bool { return strings.Contains(line, "Foo") })
		barLine := mdFind(lines, func(line string) bool { return strings.Contains(line, "bar") })
		mdAssert(t, fooLine, "fooLine")
		mdAssert(t, barLine, "barLine")
		mdAssert(t, strings.Contains(fooLine, "\u001b[3m"), "fooLine?.includes(\"\\x1b[3m\")")
		mdAssert(t, strings.Contains(barLine, "\u001b[3m"), "barLine?.includes(\"\\x1b[3m\")")
		mdAssert(t, !strings.Contains(fooLine, "\u001b[35m"), "!fooLine?.includes(\"\\x1b[35m\")")
		mdAssert(t, !strings.Contains(barLine, "\u001b[35m"), "!barLine?.includes(\"\\x1b[35m\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1337
	t.Run("should apply consistent styling to explicit multiline blockquote", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions(">Foo\n>bar", 0, 0, mdUpstreamTheme(), &DefaultTextStyle{Color: mdChalk("cyan")}, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		quotedLines := mdFilter(plainLines, func(line string) bool { return strings.HasPrefix(line, "│ ") })
		mdEqual(t, mdLen(quotedLines), 2)
		fooLine := mdFind(lines, func(line string) bool { return strings.Contains(line, "Foo") })
		barLine := mdFind(lines, func(line string) bool { return strings.Contains(line, "bar") })
		mdAssert(t, strings.Contains(fooLine, "\u001b[3m"), "fooLine?.includes(\"\\x1b[3m\")")
		mdAssert(t, strings.Contains(barLine, "\u001b[3m"), "barLine?.includes(\"\\x1b[3m\")")
		mdAssert(t, !strings.Contains(fooLine, "\u001b[36m"), "!fooLine?.includes(\"\\x1b[36m\")")
		mdAssert(t, !strings.Contains(barLine, "\u001b[36m"), "!barLine?.includes(\"\\x1b[36m\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1367
	t.Run("should render list content inside blockquotes", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("> 1. bla bla\n> - nested bullet", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		quotedLines := mdFilter(plainLines, func(line string) bool { return strings.HasPrefix(line, "│ ") })
		mdAssert(t, slices.ContainsFunc(quotedLines, func(line string) bool { return strings.Contains(line, "1. bla bla") }), "quotedLines.some((line) => line.includes(\"1. bla bla\"))")
		mdAssert(t, slices.ContainsFunc(quotedLines, func(line string) bool { return strings.Contains(line, "- nested bullet") }), "quotedLines.some((line) => line.includes(\"- nested bullet\"))")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1390
	t.Run("should wrap long blockquote lines and add border to each wrapped line", func(t *testing.T) {
		mdCaseSetup(t)
		longText := "This is a very long blockquote line that should wrap to multiple lines when rendered"
		markdown := NewMarkdownWithOptions(("> " + longText + ""), 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(30)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		contentLines := mdFilter(plainLines, func(line string) bool { return (mdLen(line) > 0) })
		mdAssert(t, (mdLen(contentLines) > 1), "contentLines.length > 1")
		for _, line := range contentLines {
			mdAssert(t, strings.HasPrefix(line, "│ "), "line.startsWith(\"│ \")")
		}
		allText := strings.Join(contentLines, " ")
		mdAssert(t, strings.Contains(allText, "very long"), "allText.includes(\"very long\")")
		mdAssert(t, strings.Contains(allText, "blockquote"), "allText.includes(\"blockquote\")")
		mdAssert(t, strings.Contains(allText, "multiple"), "allText.includes(\"multiple\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1416
	t.Run("should properly indent wrapped blockquote lines with styling", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("> This is styled text that is long enough to wrap", 0, 0, mdUpstreamTheme(), &DefaultTextStyle{Color: mdChalk("yellow"), Italic: true}, nil)
		lines := markdown.Render(25)
		plainLines := mdMap(lines, func(line string) string { return widthx.JSTrimEnd(mdReplace(line, "\\x1b\\[[0-9;]*m", "")) })
		contentLines := mdFilter(plainLines, func(line string) bool { return (mdLen(line) > 0) })
		for _, line := range contentLines {
			mdAssert(t, strings.HasPrefix(line, "│ "), "line.startsWith(\"│ \")")
		}
		allOutput := strings.Join(lines, "\n")
		mdAssert(t, strings.Contains(allOutput, "\u001b[3m"), "allOutput.includes(\"\\x1b[3m\")")
		mdAssert(t, !strings.Contains(allOutput, "\u001b[33m"), "!allOutput.includes(\"\\x1b[33m\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1447
	t.Run("should render inline formatting inside blockquotes and reapply quote styling after", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("> Quote with **bold** and `code`", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		mdAssert(t, slices.ContainsFunc(plainLines, func(line string) bool { return strings.HasPrefix(line, "│ ") }), "plainLines.some((line) => line.startsWith(\"│ \"))")
		allPlain := strings.Join(plainLines, " ")
		mdAssert(t, strings.Contains(allPlain, "Quote with"), "allPlain.includes(\"Quote with\")")
		mdAssert(t, strings.Contains(allPlain, "bold"), "allPlain.includes(\"bold\")")
		mdAssert(t, strings.Contains(allPlain, "code"), "allPlain.includes(\"code\")")
		allOutput := strings.Join(lines, "\n")
		mdAssert(t, strings.Contains(allOutput, "\u001b[1m"), "allOutput.includes(\"\\x1b[1m\")")
		mdAssert(t, strings.Contains(allOutput, "\u001b[33m"), "allOutput.includes(\"\\x1b[33m\")")
		mdAssert(t, strings.Contains(allOutput, "\u001b[3m"), "allOutput.includes(\"\\x1b[3m\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1479
	t.Run("should preserve heading styling after inline code", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("### Why `sourceInfo` should not be optional", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		joinedOutput := strings.Join(lines, "\n")
		mdAssert(t, strings.Contains(joinedOutput, "\u001b[33m"), "joinedOutput.includes(\"\\x1b[33m\")")
		afterCodeIndex := strings.Index(joinedOutput, "should not be optional")
		mdAssert(t, (afterCodeIndex > 0), "afterCodeIndex > 0")
		precedingChunk := mdStringSlice(joinedOutput, max(0, (afterCodeIndex-40)), afterCodeIndex)
		mdAssert(t, strings.Contains(precedingChunk, "\u001b[1m"), "precedingChunk.includes(\"\\x1b[1m\")")
		mdAssert(t, strings.Contains(precedingChunk, "\u001b[36m"), "precedingChunk.includes(\"\\x1b[36m\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1508
	t.Run("should preserve heading styling after inline code for h1", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("# Title with `code` inside", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		joinedOutput := strings.Join(lines, "\n")
		afterCodeIndex := strings.Index(joinedOutput, "inside")
		mdAssert(t, (afterCodeIndex > 0), "afterCodeIndex > 0")
		precedingChunk := mdStringSlice(joinedOutput, max(0, (afterCodeIndex-40)), afterCodeIndex)
		mdAssert(t, strings.Contains(precedingChunk, "\u001b[1m"), "precedingChunk.includes(\"\\x1b[1m\")")
		mdAssert(t, strings.Contains(precedingChunk, "\u001b[36m"), "precedingChunk.includes(\"\\x1b[36m\")")
		mdAssert(t, strings.Contains(precedingChunk, "\u001b[4m"), "precedingChunk.includes(\"\\x1b[4m\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1524
	t.Run("should not leak h1 underline into padding when inline code is the last token", func(t *testing.T) {
		mdCaseSetup(t)
		testMDHeadingPadding(t)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1548
	t.Run("should preserve heading styling after bold text", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("## Heading with **bold** and more", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		joinedOutput := strings.Join(lines, "\n")
		afterBoldIndex := strings.Index(joinedOutput, "and more")
		mdAssert(t, (afterBoldIndex > 0), "afterBoldIndex > 0")
		precedingChunk := mdStringSlice(joinedOutput, max(0, (afterBoldIndex-40)), afterBoldIndex)
		mdAssert(t, strings.Contains(precedingChunk, "\u001b[1m"), "precedingChunk.includes(\"\\x1b[1m\")")
		mdAssert(t, strings.Contains(precedingChunk, "\u001b[36m"), "precedingChunk.includes(\"\\x1b[36m\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1564
	t.Run("should render ~~text~~ as strikethrough", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("Use ~~strikethrough~~ here", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		joinedOutput := strings.Join(lines, "\n")
		joinedPlain := strings.Join(mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") }), " ")
		mdAssert(t, strings.Contains(joinedOutput, "\u001b[9m"), "joinedOutput.includes(\"\\x1b[9m\")")
		mdAssert(t, strings.Contains(joinedPlain, "strikethrough"), "joinedPlain.includes(\"strikethrough\")")
		mdAssert(t, !strings.Contains(joinedPlain, "~~strikethrough~~"), "!joinedPlain.includes(\"~~strikethrough~~\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1576
	t.Run("should keep ~text~ as plain text", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("Use ~strikethrough~ literally", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		joinedOutput := strings.Join(lines, "\n")
		joinedPlain := strings.Join(mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") }), " ")
		mdAssert(t, strings.Contains(joinedPlain, "~strikethrough~"), "joinedPlain.includes(\"~strikethrough~\")")
		mdAssert(t, !strings.Contains(joinedOutput, "\u001b[9m"), "!joinedOutput.includes(\"\\x1b[9m\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1593
	t.Run("should not duplicate URL for autolinked emails", func(t *testing.T) {
		mdCaseSetup(t)
		SetCapabilities(TerminalCapabilities{TrueColor: false, Hyperlinks: false})
		markdown := NewMarkdownWithOptions("Contact user@example.com for help", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		joinedPlain := strings.Join(plainLines, " ")
		mdAssert(t, strings.Contains(joinedPlain, "user@example.com"), "joinedPlain.includes(\"user@example.com\")")
		mdAssert(t, !strings.Contains(joinedPlain, "mailto:"), "!joinedPlain.includes(\"mailto:\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1607
	t.Run("should not duplicate URL for bare URLs", func(t *testing.T) {
		mdCaseSetup(t)
		SetCapabilities(TerminalCapabilities{TrueColor: false, Hyperlinks: false})
		markdown := NewMarkdownWithOptions("Visit https://example.com for more", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		joinedPlain := strings.Join(plainLines, " ")
		urlCount := mdLen((mdMatches(joinedPlain, "https:\\/\\/example\\.com")))
		mdEqual(t, urlCount, 1)
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1620
	t.Run("should show URL in parentheses when hyperlinks are not supported", func(t *testing.T) {
		mdCaseSetup(t)
		SetCapabilities(TerminalCapabilities{TrueColor: false, Hyperlinks: false})
		markdown := NewMarkdownWithOptions("[click here](https://example.com)", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		joinedPlain := strings.Join(plainLines, " ")
		mdAssert(t, strings.Contains(joinedPlain, "click here"), "joinedPlain.includes(\"click here\")")
		mdAssert(t, strings.Contains(joinedPlain, "(https://example.com)"), "joinedPlain.includes(\"(https://example.com)\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1632
	t.Run("should show mailto URL in parentheses when hyperlinks are not supported", func(t *testing.T) {
		mdCaseSetup(t)
		SetCapabilities(TerminalCapabilities{TrueColor: false, Hyperlinks: false})
		markdown := NewMarkdownWithOptions("[Email me](mailto:test@example.com)", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		joinedPlain := strings.Join(plainLines, " ")
		mdAssert(t, strings.Contains(joinedPlain, "Email me"), "joinedPlain.includes(\"Email me\")")
		mdAssert(t, strings.Contains(joinedPlain, "(mailto:test@example.com)"), "joinedPlain.includes(\"(mailto:test@example.com)\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1644
	t.Run("should emit OSC 8 hyperlink sequence when terminal supports hyperlinks", func(t *testing.T) {
		mdCaseSetup(t)
		SetCapabilities(TerminalCapabilities{TrueColor: false, Hyperlinks: true})
		markdown := NewMarkdownWithOptions("[click here](https://example.com)", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		joined := strings.Join(lines, "")
		mdAssert(t, strings.Contains(joined, "\u001b]8;;https://example.com\u001b\\"), "joined.includes(\"\\x1b]8;;https://example.com\\x1b\\\\\")")
		mdAssert(t, strings.Contains(joined, "\u001b]8;;\u001b\\"), "joined.includes(\"\\x1b]8;;\\x1b\\\\\")")
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b[^a-zA-Z]*[a-zA-Z]|\\x1b\\].*?\\x1b\\\\", "") })
		mdAssert(t, strings.Contains(strings.Join(plainLines, ""), "click here"), "plainLines.join(\"\").includes(\"click here\")")
		rawPlain := mdMap(lines, func(line string) string {
			return mdReplace(mdReplace(line, "\\x1b\\]8;;[^\\x1b]*\\x1b\\\\", ""), "\\x1b\\[[0-9;]*m", "")
		})
		mdAssert(t, !strings.Contains(strings.Join(rawPlain, ""), "(https://example.com)"), "!rawPlain.join(\"\").includes(\"(https://example.com)\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1665
	t.Run("should use OSC 8 for mailto links when terminal supports hyperlinks", func(t *testing.T) {
		mdCaseSetup(t)
		SetCapabilities(TerminalCapabilities{TrueColor: false, Hyperlinks: true})
		markdown := NewMarkdownWithOptions("[Email me](mailto:test@example.com)", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		joined := strings.Join(lines, "")
		mdAssert(t, strings.Contains(joined, "\u001b]8;;mailto:test@example.com\u001b\\"), "joined.includes(\"\\x1b]8;;mailto:test@example.com\\x1b\\\\\")")
		mdAssert(t, strings.Contains(joined, "\u001b]8;;\u001b\\"), "joined.includes(\"\\x1b]8;;\\x1b\\\\\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1679
	t.Run("should use OSC 8 for bare URLs when terminal supports hyperlinks", func(t *testing.T) {
		mdCaseSetup(t)
		SetCapabilities(TerminalCapabilities{TrueColor: false, Hyperlinks: true})
		markdown := NewMarkdownWithOptions("Visit https://example.com for more", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		joined := strings.Join(lines, "")
		mdAssert(t, strings.Contains(joined, "\u001b]8;;https://example.com\u001b\\"), "joined.includes(\"\\x1b]8;;https://example.com\\x1b\\\\\")")
		rawPlain := mdMap(lines, func(line string) string {
			return mdReplace(mdReplace(line, "\\x1b\\]8;;[^\\x1b]*\\x1b\\\\", ""), "\\x1b\\[[0-9;]*m", "")
		})
		mdAssert(t, !strings.Contains(strings.Join(rawPlain, ""), "(https://example.com)"), "!rawPlain.join(\"\").includes(\"(https://example.com)\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1696
	t.Run("should render content with HTML-like tags as text", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("This is text with <thinking>hidden content</thinking> that should be visible", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		joinedPlain := strings.Join(plainLines, " ")
		mdAssert(t, (strings.Contains(joinedPlain, "hidden content") || strings.Contains(joinedPlain, "<thinking>")), "joinedPlain.includes(\"hidden content\") || joinedPlain.includes(\"<thinking>\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1717
	t.Run("should render HTML tags in code blocks correctly", func(t *testing.T) {
		mdCaseSetup(t)
		markdown := NewMarkdownWithOptions("```html\n<div>Some HTML</div>\n```", 0, 0, mdUpstreamTheme(), nil, nil)
		lines := markdown.Render(80)
		plainLines := mdMap(lines, func(line string) string { return mdReplace(line, "\\x1b\\[[0-9;]*m", "") })
		joinedPlain := strings.Join(plainLines, "\n")
		mdAssert(t, (strings.Contains(joinedPlain, "<div>") && strings.Contains(joinedPlain, "</div>")), "joinedPlain.includes(\"<div>\") && joinedPlain.includes(\"</div>\")")
	})
	// .upstream/v0.87.1/packages/tui/test/markdown.test.ts:1733
	t.Run("stabilizes partial closing fence rendering", func(t *testing.T) {
		mdCaseSetup(t)
		testMDStreamingFences(t)
	})
}
