// Code generated by test/parity/testdata/overlay-non-capturing-tests.mjs; DO NOT EDIT.
package tui

import "testing"

func TestUpstreamOverlayNonCapturing(t *testing.T) {
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:57
	t.Run("non-capturing overlay preserves focus on creation", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, overlay.focused, false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:75
	t.Run("focus() transfers focus to the overlay", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.focus()
		terminal.flush(t)
		ncEqual(t, editor.focused, false)
		ncEqual(t, overlay.focused, true)
		ncEqual(t, handle.isFocused(), true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:95
	t.Run("unfocus() restores previous focus", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.focus()
		handle.unfocus()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, overlay.focused, false)
		ncEqual(t, handle.isFocused(), false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:116
	t.Run("setHidden(false) on non-capturing overlay does not auto-focus", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.setHidden(true)
		handle.setHidden(false)
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, overlay.focused, false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:136
	t.Run("hide() when overlay is not focused does not change focus", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.Close()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:154
	t.Run("hide() when focused restores focus correctly", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.focus()
		handle.Close()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, overlay.focused, false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:174
	t.Run("capturing overlay removed with non-capturing below restores focus to editor", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		nonCapturing := &ncUpstreamComponent{lines: []string{"NC"}}
		capturing := &ncUpstreamComponent{lines: []string{"CAP"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(nonCapturing, OverlayOptions{nonCapturing: true})
		handle := tui.OpenOverlay(capturing, OverlayOptions{})
		ncEqual(t, capturing.focused, true)
		handle.Close()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, nonCapturing.focused, false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:196
	t.Run("sub-overlay cleanup then hideOverlay restores focus and input to editor", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		timer := &ncUpstreamComponent{lines: []string{"TIMER"}}
		controller := &ncUpstreamComponent{lines: []string{"CTRL"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		timerHandle := tui.OpenOverlay(timer, OverlayOptions{nonCapturing: true})
		tui.OpenOverlay(controller, OverlayOptions{})
		ncEqual(t, controller.focused, true)
		ncEqual(t, editor.focused, false)
		timerHandle.Close()
		tui.hideOverlay()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, controller.focused, false)
		ncEqual(t, timer.focused, false)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, editor.inputs, []string{"x"})
		ncInputsEqual(t, controller.inputs, []string{})
		ncInputsEqual(t, timer.inputs, []string{})
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:226
	t.Run("removed focused child overlay does not become parent overlay fallback", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		child := &ncUpstreamComponent{lines: []string{"CHILD"}}
		parent := &ncUpstreamComponent{lines: []string{"PARENT"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		childHandle := tui.OpenOverlay(child, OverlayOptions{nonCapturing: true})
		childHandle.focus()
		parentHandle := tui.OpenOverlay(parent, OverlayOptions{})
		ncEqual(t, parent.focused, true)
		childHandle.Close()
		parentHandle.Close()
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, editor.inputs, []string{"x"})
		ncInputsEqual(t, child.inputs, []string{})
		ncInputsEqual(t, parent.inputs, []string{})
		ncEqual(t, editor.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:255
	t.Run("microtask-deferred sub-overlay pattern (showExtensionCustom simulation) restores focus", func(t *testing.T) {
		testNCUpstreamMicrotaskCleanup(t)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:311
	t.Run("handleInput redirection skips non-capturing overlays when focused overlay becomes invisible", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		fallbackCapturing := &ncUpstreamComponent{lines: []string{"FALLBACK"}}
		nonCapturing := &ncUpstreamComponent{lines: []string{"NC"}}
		primary := &ncUpstreamComponent{lines: []string{"PRIMARY"}}
		isVisible := true
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(fallbackCapturing, OverlayOptions{})
		tui.OpenOverlay(nonCapturing, OverlayOptions{nonCapturing: true})
		tui.OpenOverlay(primary, OverlayOptions{visible: func(int, int) bool { return isVisible }})
		ncEqual(t, primary.focused, true)
		isVisible = false
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, primary.inputs, []string{})
		ncInputsEqual(t, nonCapturing.inputs, []string{})
		ncInputsEqual(t, fallbackCapturing.inputs, []string{"x"})
		ncEqual(t, fallbackCapturing.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:339
	t.Run("active base focus replacement receives close input before overlay restore", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		replacement := &ncUpstreamComponent{lines: []string{"REPLACEMENT"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		overlay.onInput = func(data string) {
			overlay.inputs = append(overlay.inputs, data)
			if data == "b" {
				tui.SetFocus(replacement)
			}
		}
		replacement.onInput = func(data string) {
			replacement.inputs = append(replacement.inputs, data)
			if data == "\r" {
				tui.SetFocus(editor)
			}
		}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(overlay, OverlayOptions{})
		ncEqual(t, overlay.focused, true)
		terminal.sendInput("b")
		terminal.flush(t)
		ncEqual(t, replacement.focused, true)
		terminal.sendInput("\r")
		terminal.flush(t)
		ncInputsEqual(t, replacement.inputs, []string{"\r"})
		ncInputsEqual(t, overlay.inputs, []string{"b"})
		ncEqual(t, overlay.focused, true)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{"b", "x"})
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:381
	t.Run("active replacement still receives input when it is another overlay preFocus", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		replacement := &ncUpstreamComponent{lines: []string{"REPLACEMENT"}}
		passive := &ncUpstreamComponent{lines: []string{"PASSIVE"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		overlay.onInput = func(data string) {
			overlay.inputs = append(overlay.inputs, data)
			if data == "b" {
				tui.SetFocus(replacement)
			}
		}
		replacement.onInput = func(data string) {
			replacement.inputs = append(replacement.inputs, data)
			if data == "\r" {
				tui.SetFocus(editor)
			}
		}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.SetFocus(replacement)
		tui.OpenOverlay(passive, OverlayOptions{nonCapturing: true})
		tui.SetFocus(editor)
		tui.OpenOverlay(overlay, OverlayOptions{})
		terminal.sendInput("b")
		terminal.flush(t)
		ncEqual(t, replacement.focused, true)
		terminal.sendInput("1")
		terminal.sendInput("\r")
		terminal.flush(t)
		ncInputsEqual(t, replacement.inputs, []string{"1", "\r"})
		ncInputsEqual(t, overlay.inputs, []string{"b"})
		ncEqual(t, overlay.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:423
	t.Run("blocked replacement can move focus internally before overlay restore", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		base := &Container{}
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		firstReplacement := &ncUpstreamComponent{lines: []string{"FIRST"}}
		secondReplacement := &ncUpstreamComponent{lines: []string{"SECOND"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		overlay.onInput = func(data string) {
			overlay.inputs = append(overlay.inputs, data)
			if data == "b" {
				tui.SetFocus(firstReplacement)
			}
		}
		firstReplacement.onInput = func(data string) {
			firstReplacement.inputs = append(firstReplacement.inputs, data)
			if data == "n" {
				tui.SetFocus(secondReplacement)
			}
		}
		secondReplacement.onInput = func(data string) {
			secondReplacement.inputs = append(secondReplacement.inputs, data)
			if data == "\r" {
				base.Clear()
				base.Add(editor)
				tui.SetFocus(editor)
			}
		}
		base.Add(editor)
		base.Add(firstReplacement)
		base.Add(secondReplacement)
		tui.Add(base)
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(overlay, OverlayOptions{})
		terminal.sendInput("b")
		terminal.flush(t)
		terminal.sendInput("n")
		terminal.flush(t)
		terminal.sendInput("2")
		terminal.sendInput("\r")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{"b"})
		ncInputsEqual(t, firstReplacement.inputs, []string{"n"})
		ncInputsEqual(t, secondReplacement.inputs, []string{"2", "\r"})
		ncEqual(t, overlay.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:472
	t.Run("removed replacement restores overlay even when overlay preFocus differs from next focus", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		base := &Container{}
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		palette := &ncUpstreamComponent{lines: []string{"PALETTE"}}
		replacement := &ncUpstreamComponent{lines: []string{"REPLACEMENT"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		overlay.onInput = func(data string) {
			overlay.inputs = append(overlay.inputs, data)
			if data == "b" {
				tui.SetFocus(replacement)
			}
		}
		replacement.onInput = func(data string) {
			replacement.inputs = append(replacement.inputs, data)
			if data == "\r" {
				base.Clear()
				base.Add(editor)
				tui.SetFocus(editor)
			}
		}
		base.Add(editor)
		base.Add(palette)
		base.Add(replacement)
		tui.Add(base)
		tui.SetFocus(palette)
		tui.Render()
		tui.OpenOverlay(overlay, OverlayOptions{})
		terminal.sendInput("b")
		terminal.flush(t)
		terminal.sendInput("\r")
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{"b", "x"})
		ncInputsEqual(t, replacement.inputs, []string{"\r"})
		ncInputsEqual(t, editor.inputs, []string{})
		ncEqual(t, overlay.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:515
	t.Run("unfocus target releases a blocked overlay while replacement remains focused", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		fallback := &ncUpstreamComponent{lines: []string{"FALLBACK"}}
		target := &ncUpstreamComponent{lines: []string{"TARGET"}}
		replacement := &ncUpstreamComponent{lines: []string{"REPLACEMENT"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		replacement.onInput = func(data string) {
			replacement.inputs = append(replacement.inputs, data)
			if data == "\r" {
				tui.SetFocus(fallback)
			}
		}
		tui.Add(&recordingComponent{})
		tui.Render()
		overlayHandle := tui.OpenOverlay(overlay, OverlayOptions{})
		overlay.onInput = func(data string) {
			overlay.inputs = append(overlay.inputs, data)
			if data == "b" {
				tui.SetFocus(replacement)
				overlayHandle.unfocus(target)
			}
		}
		terminal.sendInput("b")
		terminal.flush(t)
		ncEqual(t, replacement.focused, true)
		terminal.sendInput("\r")
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{"b"})
		ncInputsEqual(t, replacement.inputs, []string{"\r"})
		ncInputsEqual(t, fallback.inputs, []string{})
		ncInputsEqual(t, target.inputs, []string{"x"})
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:554
	t.Run("handleInput restores focus to a visible focused overlay after base focus steal", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		replacement := &ncUpstreamComponent{lines: []string{"REPLACEMENT"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(overlay, OverlayOptions{})
		ncEqual(t, overlay.focused, true)
		tui.SetFocus(replacement)
		tui.SetFocus(editor)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{"x"})
		ncInputsEqual(t, editor.inputs, []string{})
		ncEqual(t, overlay.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:578
	t.Run("handleInput restores focus to explicitly focused raw sub-overlay after base focus steal", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		controller := &ncUpstreamComponent{lines: []string{"CONTROLLER"}}
		subOverlay := &ncUpstreamComponent{lines: []string{"SUB"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(controller, OverlayOptions{})
		subHandle := tui.OpenOverlay(subOverlay, OverlayOptions{nonCapturing: true})
		subHandle.focus()
		tui.SetFocus(editor)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, subOverlay.inputs, []string{"x"})
		ncInputsEqual(t, controller.inputs, []string{})
		ncInputsEqual(t, editor.inputs, []string{})
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:602
	t.Run("passive non-capturing overlay does not regain input after base focus", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		passive := &ncUpstreamComponent{lines: []string{"PASSIVE"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(passive, OverlayOptions{nonCapturing: true})
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, editor.inputs, []string{"x"})
		ncInputsEqual(t, passive.inputs, []string{})
		ncEqual(t, editor.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:622
	t.Run("explicitly focused non-capturing overlay regains input after base focus steal", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"NC"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.focus()
		tui.SetFocus(editor)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{"x"})
		ncInputsEqual(t, editor.inputs, []string{})
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:643
	t.Run("unfocus() prevents visible overlay from regaining input", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{})
		handle.unfocus()
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, editor.inputs, []string{"x"})
		ncInputsEqual(t, overlay.inputs, []string{})
		ncEqual(t, editor.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:664
	t.Run("setFocus(null) explicitly clears visible overlay restore", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.Render()
		tui.OpenOverlay(overlay, OverlayOptions{})
		tui.SetFocus(nil)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{})
		ncEqual(t, overlay.focused, false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:682
	t.Run("blocked replacement setFocus(null) resumes the visible overlay", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		replacement := &ncUpstreamComponent{lines: []string{"REPLACEMENT"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		replacement.onInput = func(data string) {
			replacement.inputs = append(replacement.inputs, data)
			if data == "\r" {
				tui.SetFocus(nil)
			}
		}
		overlay.onInput = func(data string) {
			overlay.inputs = append(overlay.inputs, data)
			if data == "b" {
				tui.SetFocus(replacement)
			}
		}
		tui.Add(&recordingComponent{})
		tui.Render()
		tui.OpenOverlay(overlay, OverlayOptions{})
		terminal.sendInput("b")
		terminal.flush(t)
		terminal.sendInput("\r")
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, replacement.inputs, []string{"\r"})
		ncInputsEqual(t, overlay.inputs, []string{"b", "x"})
		ncEqual(t, overlay.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:712
	t.Run("temporarily invisible focused overlay falls back without losing restore eligibility", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		visible := true
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(overlay, OverlayOptions{visible: func(int, int) bool { return visible }})
		tui.SetFocus(editor)
		visible = false
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, editor.inputs, []string{"x"})
		ncInputsEqual(t, overlay.inputs, []string{})
		visible = true
		terminal.sendInput("y")
		terminal.flush(t)
		ncInputsEqual(t, editor.inputs, []string{"x"})
		ncInputsEqual(t, overlay.inputs, []string{"y"})
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:739
	t.Run("temporarily invisible focused overlay with null preFocus restores when visible again", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		visible := true
		tui.Add(&recordingComponent{})
		tui.Render()
		tui.OpenOverlay(overlay, OverlayOptions{visible: func(int, int) bool { return visible }})
		visible = false
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{})
		visible = true
		terminal.sendInput("y")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{"y"})
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:761
	t.Run("cyclic overlay preFocus ancestry does not hang focus changes", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(overlay)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.focus()
		tui.SetFocus(editor)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, editor.inputs, []string{"x"})
		ncInputsEqual(t, overlay.inputs, []string{})
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:782
	t.Run("handleInput restores the focus-order top overlay after base focus steal", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		lower := &ncUpstreamComponent{lines: []string{"LOWER"}}
		upper := &ncUpstreamComponent{lines: []string{"UPPER"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		lowerHandle := tui.OpenOverlay(lower, OverlayOptions{})
		tui.OpenOverlay(upper, OverlayOptions{})
		lowerHandle.focus()
		tui.SetFocus(editor)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, lower.inputs, []string{"x"})
		ncInputsEqual(t, upper.inputs, []string{})
		ncInputsEqual(t, editor.inputs, []string{})
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:806
	t.Run("hideOverlay() does not reassign focus when topmost overlay is non-capturing", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		capturing := &ncUpstreamComponent{lines: []string{"CAP"}}
		nonCapturing := &ncUpstreamComponent{lines: []string{"NC"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		tui.OpenOverlay(capturing, OverlayOptions{})
		tui.OpenOverlay(nonCapturing, OverlayOptions{nonCapturing: true})
		ncEqual(t, capturing.focused, true)
		tui.hideOverlay()
		terminal.flush(t)
		ncEqual(t, capturing.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:827
	t.Run("multiple capturing and non-capturing overlays restore focus through removals", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		c1 := &ncUpstreamComponent{lines: []string{"C1"}}
		n1 := &ncUpstreamComponent{lines: []string{"N1"}}
		c2 := &ncUpstreamComponent{lines: []string{"C2"}}
		n2 := &ncUpstreamComponent{lines: []string{"N2"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		c1Handle := tui.OpenOverlay(c1, OverlayOptions{})
		tui.OpenOverlay(n1, OverlayOptions{nonCapturing: true})
		c2Handle := tui.OpenOverlay(c2, OverlayOptions{})
		tui.OpenOverlay(n2, OverlayOptions{nonCapturing: true})
		ncEqual(t, c2.focused, true)
		c2Handle.Close()
		terminal.flush(t)
		ncEqual(t, c1.focused, true)
		c1Handle.Close()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:855
	t.Run("capturing overlay unfocus() on topmost capturing overlay falls back to preFocus", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		capturing := &ncUpstreamComponent{lines: []string{"CAP"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(capturing, OverlayOptions{})
		ncEqual(t, capturing.focused, true)
		handle.unfocus()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, capturing.focused, false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:877
	t.Run("focus() on hidden overlay is a no-op", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.setHidden(true)
		handle.focus()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, handle.isFocused(), false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:897
	t.Run("focus() after hide() is a no-op", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.Close()
		handle.focus()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, handle.isFocused(), false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:917
	t.Run("unfocus() when overlay does not have focus is a no-op", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{nonCapturing: true})
		handle.unfocus()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, overlay.focused, false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:936
	t.Run("unfocus() with null preFocus clears focus and does not route input back to overlay", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{})
		ncEqual(t, overlay.focused, true)
		handle.unfocus()
		ncEqual(t, overlay.focused, false)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{})
		ncEqual(t, handle.isFocused(), false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:958
	t.Run("toggle focus between non-capturing overlays then unfocus returns to editor", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		a := &ncUpstreamComponent{lines: []string{"A"}}
		b := &ncUpstreamComponent{lines: []string{"B"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		aHandle := tui.OpenOverlay(a, OverlayOptions{nonCapturing: true})
		bHandle := tui.OpenOverlay(b, OverlayOptions{nonCapturing: true})
		aHandle.focus()
		bHandle.focus()
		aHandle.focus()
		aHandle.unfocus()
		terminal.flush(t)
		ncEqual(t, editor.focused, true)
		ncEqual(t, a.focused, false)
		ncEqual(t, b.focused, false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:983
	t.Run("explicit unfocus target supports cycling between three overlays and editor", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		a := &ncUpstreamComponent{lines: []string{"A"}}
		b := &ncUpstreamComponent{lines: []string{"B"}}
		c := &ncUpstreamComponent{lines: []string{"C"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		aHandle := tui.OpenOverlay(a, OverlayOptions{})
		bHandle := tui.OpenOverlay(b, OverlayOptions{})
		cHandle := tui.OpenOverlay(c, OverlayOptions{})
		aHandle.focus()
		terminal.sendInput("a")
		terminal.flush(t)
		bHandle.focus()
		terminal.sendInput("b")
		terminal.flush(t)
		cHandle.focus()
		terminal.sendInput("c")
		terminal.flush(t)
		cHandle.unfocus(editor)
		terminal.sendInput("e")
		terminal.flush(t)
		aHandle.focus()
		terminal.sendInput("A")
		terminal.flush(t)
		aHandle.unfocus(editor)
		terminal.sendInput("E")
		terminal.flush(t)
		ncInputsEqual(t, a.inputs, []string{"a", "A"})
		ncInputsEqual(t, b.inputs, []string{"b"})
		ncInputsEqual(t, c.inputs, []string{"c"})
		ncInputsEqual(t, editor.inputs, []string{"e", "E"})
		ncEqual(t, editor.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:1027
	t.Run("explicit null unfocus target clears focus without restoring overlays", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		overlay := &ncUpstreamComponent{lines: []string{"OVERLAY"}}
		tui.Add(&recordingComponent{})
		tui.Render()
		handle := tui.OpenOverlay(overlay, OverlayOptions{})
		handle.unfocus(nil)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, overlay.inputs, []string{})
		ncEqual(t, handle.isFocused(), false)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:1045
	t.Run("hiding focused overlay falls back to next visual-frontmost overlay", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(80, 24)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		a := &ncUpstreamComponent{lines: []string{"A"}}
		b := &ncUpstreamComponent{lines: []string{"B"}}
		c := &ncUpstreamComponent{lines: []string{"C"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		aHandle := tui.OpenOverlay(a, OverlayOptions{})
		bHandle := tui.OpenOverlay(b, OverlayOptions{})
		tui.OpenOverlay(c, OverlayOptions{})
		aHandle.focus()
		bHandle.focus()
		bHandle.setHidden(true)
		terminal.sendInput("x")
		terminal.flush(t)
		ncInputsEqual(t, a.inputs, []string{"x"})
		ncInputsEqual(t, c.inputs, []string{})
		ncEqual(t, a.focused, true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:1074
	t.Run("focus() on already-focused overlay bumps visual order", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(20, 6)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		aHandle := tui.OpenOverlay(&recordingComponent{lines: []string{"A"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		tui.OpenOverlay(&recordingComponent{lines: []string{"B"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		aHandle.focus()
		tui.OpenOverlay(&recordingComponent{lines: []string{"C"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "C")
		aHandle.focus()
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "A")
		ncEqual(t, aHandle.isFocused(), true)
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:1097
	t.Run("default rendering order for overlapping overlays follows creation order", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(20, 6)
		tui := terminal.newTUI(t)
		tui.Add(&recordingComponent{})
		tui.Render()
		tui.OpenOverlay(&recordingComponent{lines: []string{"A"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		tui.OpenOverlay(&recordingComponent{lines: []string{"B"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "B")
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:1112
	t.Run("focus() on lower overlay renders it on top", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(20, 6)
		tui := terminal.newTUI(t)
		tui.Add(&recordingComponent{})
		tui.Render()
		lower := tui.OpenOverlay(&recordingComponent{lines: []string{"A"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		tui.OpenOverlay(&recordingComponent{lines: []string{"B"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "B")
		lower.focus()
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "A")
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:1130
	t.Run("focusing middle overlay places it on top while preserving others relative order", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(20, 6)
		tui := terminal.newTUI(t)
		tui.Add(&recordingComponent{})
		tui.Render()
		tui.OpenOverlay(&recordingComponent{lines: []string{"A"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		middle := tui.OpenOverlay(&recordingComponent{lines: []string{"B"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		top := tui.OpenOverlay(&recordingComponent{lines: []string{"C"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "C")
		middle.focus()
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "B")
		middle.Close()
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "C")
		top.Close()
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "A")
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:1155
	t.Run("capturing overlay hidden and shown again renders on top after unhide", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(20, 6)
		tui := terminal.newTUI(t)
		tui.Add(&recordingComponent{})
		tui.Render()
		tui.OpenOverlay(&recordingComponent{lines: []string{"A"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		capturing := tui.OpenOverlay(&recordingComponent{lines: []string{"B"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1)})
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "B")
		capturing.setHidden(true)
		tui.OpenOverlay(&recordingComponent{lines: []string{"C"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "C")
		capturing.setHidden(false)
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "B")
	})
	// .upstream/v0.87.1/packages/tui/test/overlay-non-capturing.test.ts:1177
	t.Run("unfocus() does not change visual order until another overlay is focused", func(t *testing.T) {
		terminal := newNCUpstreamTerminal(20, 6)
		tui := terminal.newTUI(t)
		editor := &ncUpstreamComponent{lines: []string{"EDITOR"}}
		tui.Add(&recordingComponent{})
		tui.SetFocus(editor)
		tui.Render()
		a := tui.OpenOverlay(&recordingComponent{lines: []string{"A"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		b := tui.OpenOverlay(&recordingComponent{lines: []string{"B"}}, OverlayOptions{row: overlayCells(0), col: overlayCells(0), width: overlayCells(1), nonCapturing: true})
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "B")
		a.focus()
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "A")
		a.unfocus()
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "A")
		b.focus()
		terminal.flush(t)
		ncEqual(t, ncFirstColumn(terminal.viewport()[0]), "B")
	})
}
