package codingagent

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"sync"
	"testing"

	"github.com/MichaelKinsy/PiG/coding/extension"
)

// This snapshot is generated by the pinned Pi transformer from the structural inputs recorded in the owning handoff; it retains exact output bytes, including normalized CR input and fences following containers.
func TestMermaidBlockScopeMatchesPinnedPi(t *testing.T) {
	file, err := os.Open("testdata/mermaid-scope-golden.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		if err := file.Close(); err != nil {
			t.Error(err)
		}
	}()
	scanner := bufio.NewScanner(file)
	seen := false
	for scanner.Scan() {
		seen = true
		var fixture struct{ Name, MD, Out string }
		if err := json.Unmarshal(scanner.Bytes(), &fixture); err != nil {
			t.Fatal(err)
		}
		t.Run(fixture.Name, func(t *testing.T) {
			transform := createMermaidMarkdownTransformer(func() string { return "streaming" }, nil)
			got := transform(fixture.MD, extension.MarkdownTransformContext{AvailableWidth: 100, MessageType: extension.MarkdownMessageAssistant})
			if got != fixture.Out {
				t.Errorf("scope/output mismatch:\ninput: %q\ngot: %q\nwant: %q", fixture.MD, got, fixture.Out)
			}
		})
	}
	if err := scanner.Err(); err != nil {
		t.Fatal(err)
	}
	if !seen {
		t.Fatal("empty pinned scope fixture")
	}
}

// Marked's definition destination uses JavaScript dot semantics: U+2028/U+2029 invalidate an angle-bracket destination, so a following fence is a top-level code token rather than part of a definition title.
func TestMermaidDefinitionDestinationPreservesJSLineTerminators(t *testing.T) {
	const fence = "```mermaid\nflowchart LR\n A --> B\n```\n"
	const diagram = "`┌───┐    ┌───┐`  \n`│ A ├───▶│ B │`  \n`└───┘    └───┘`\n"
	for _, tc := range []struct {
		name, separator string
		definition      bool
	}{
		{"ordinary destination", "x", true},
		{"line separator", "\u2028", false},
		{"paragraph separator", "\u2029", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			prefix := "[a]: <one" + tc.separator + "two> \"title\n"
			input := prefix + fence + "\"\n"
			want := prefix + diagram + "\"\n"
			if tc.definition {
				want = input
			}
			transform := createMermaidMarkdownTransformer(func() string { return "streaming" }, nil)
			got := transform(input, extension.MarkdownTransformContext{AvailableWidth: 100, MessageType: extension.MarkdownMessageAssistant})
			if got != want {
				t.Fatalf("definition boundary output = %q, want pinned Pi %q", got, want)
			}
		})
	}
}

// Marked's heading rules decide whether the following reference definition starts a new block or stays in paragraph text. Keep that decision faithful before selecting Mermaid fences.
func TestMermaidHeadingBoundariesMatchMarked(t *testing.T) {
	const tail = "[a]: /url \"title\n```mermaid\nflowchart LR\n A --> B\n```\n\"\n"
	const renderedTail = "[a]: /url \"title\n`┌───┐    ┌───┐`  \n`│ A ├───▶│ B │`  \n`└───┘    └───┘`\n\"\n"
	for _, tc := range []struct {
		name, prefix string
		heading      bool
	}{
		{"ATX ordinary", "# heading\n", true},
		{"ATX LS", "# one\u2028two\n", false},
		{"ATX PS", "# one\u2029two\n", false},
		{"ATX NBSP", "#\u00a0heading\n", true},
		{"ATX NEL", "#\u0085heading\n", false},
		{"setext ordinary", "heading\n===\n", true},
		{"setext LS", "one\u2028two\n===\n", false},
		{"setext PS", "one\u2029two\n===\n", false},
		{"setext TAB", "heading\n===\t\n", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			want := tc.prefix + renderedTail
			if tc.heading {
				want = tc.prefix + tail
			}
			transform := createMermaidMarkdownTransformer(func() string { return "streaming" }, nil)
			got := transform(tc.prefix+tail, extension.MarkdownTransformContext{AvailableWidth: 100, MessageType: extension.MarkdownMessageAssistant})
			if got != want {
				t.Fatalf("heading ownership = %q, want pinned Pi %q", got, want)
			}
		})
	}
}

// Marked's default GFM table owns ordinary body rows, including equals bars and reference-looking text; those rows must not become a setext heading followed by a definition that swallows the next root fence.
func TestMermaidTableRowsDoNotChangeFollowingFenceOwnership(t *testing.T) {
	const tail = "[a]: /url \"title\n```mermaid\nflowchart LR\n A --> B\n```\n\"\n"
	const renderedTail = "[a]: /url \"title\n`┌───┐    ┌───┐`  \n`│ A ├───▶│ B │`  \n`└───┘    └───┘`\n\"\n"
	for _, tc := range []struct {
		prefix     string
		definition bool
	}{
		{"a | b\n--- | ---\n===\n", false},
		{"a | b\n--- | ---\nrow\n===\n", false},
		{"a | b\n--- | ---\n", false},
		{"a\n--- | ---\n===\n", false},
		{"a | b\n---\t| ---\n===\n", true},
		{"a \\\\| b\n--- | ---\n===\n", false},
		{"a | b\n--- | ---\ntext\n", false},
		{"a | b\n--- | ---\n\n", true},
	} {
		t.Run(tc.prefix, func(t *testing.T) {
			transform := createMermaidMarkdownTransformer(func() string { return "streaming" }, nil)
			got := transform(tc.prefix+tail, extension.MarkdownTransformContext{AvailableWidth: 100, MessageType: extension.MarkdownMessageAssistant})
			want := tc.prefix + renderedTail
			if tc.definition {
				want = tc.prefix + tail
			}
			if got != want {
				t.Fatalf("table ownership = %q, want pinned Pi %q", got, want)
			}
		})
	}
}

func TestMermaidBlockScopeConcurrent(t *testing.T) {
	const diagram = "```mermaid\nflowchart LR\n A --> B\n```\n"
	input := "<div>\n" + diagram + "</div>\n\n" + diagram
	transform := createMermaidMarkdownTransformer(func() string { return "streaming" }, nil)
	context := extension.MarkdownTransformContext{AvailableWidth: 100, MessageType: extension.MarkdownMessageAssistant}
	want := transform(input, context)
	var workers sync.WaitGroup
	for range 8 {
		workers.Go(func() {
			for range 20 {
				if got := transform(input, context); got != want {
					t.Errorf("concurrent tokenization changed output: %q", got)
				}
			}
		})
	}
	workers.Wait()
}

func BenchmarkMermaidBlockScope(b *testing.B) {
	const nested = "- example\n  ```mermaid\n  flowchart LR\n   A --> B\n  ```\n\n"
	for _, repeats := range []int{1, 1000} {
		input := strings.Repeat(nested, repeats)
		b.Run(fmt.Sprint(repeats), func(b *testing.B) {
			transform := createMermaidMarkdownTransformer(func() string { return "streaming" }, nil)
			context := extension.MarkdownTransformContext{AvailableWidth: 100, MessageType: extension.MarkdownMessageAssistant}
			b.ReportAllocs()
			b.SetBytes(int64(len(input)))
			for b.Loop() {
				if got := transform(input, context); got != input {
					b.Fatal("nested code changed")
				}
			}
		})
	}
}

// Pi mermaid.ts:72-76 transforms top-level Marked code tokens only, never code nested in another token.
func TestReviewMermaidOnlyTopLevelFences(t *testing.T) {
	for _, tc := range []struct{ name, markdown string }{
		{"inside non-Mermaid fence", "````text\n```mermaid\nflowchart LR\n A --> B\n```\n````\n"},
		{"inside HTML block", "<div>\n```mermaid\nflowchart LR\n A --> B\n```\n</div>\n"},
		{"raw HTML requires matching closer", "<script>\ntext\n</style>\n```mermaid\nflowchart LR\n A --> B\n```\n"},
		{"inside list", "- Example\n  ```mermaid\n  flowchart LR\n    A --> B\n  ```\n"},
		{"inside same-line reference title", "[a]: /url \"title\n```mermaid\nflowchart LR\n A --> B\n```\n\"\n"},
		{"inside next-line reference title", "[a]: /url\n \"title\n```mermaid\nflowchart LR\n A --> B\n```\n\"\n"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			transform := createMermaidMarkdownTransformer(func() string { return "streaming" }, nil)
			got := transform(tc.markdown, extension.MarkdownTransformContext{AvailableWidth: 100, MessageType: extension.MarkdownMessageAssistant})
			if got != tc.markdown {
				t.Errorf("nested Mermaid transformed: got %q; want raw %q", got, tc.markdown)
			}
		})
	}
}
