// Command gen-image-models imports a published Pi image catalog or a strict OpenRouter response and emits ai/image_models_generated.go.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
)

type imageModel struct {
	ID       string            `json:"id"`
	Name     string            `json:"name"`
	API      string            `json:"api"`
	Provider string            `json:"provider"`
	BaseURL  string            `json:"baseUrl"`
	Headers  map[string]string `json:"headers,omitempty"`
	Input    []string          `json:"input"`
	Output   []string          `json:"output"`
	Cost     struct {
		Input      float64 `json:"input"`
		Output     float64 `json:"output"`
		CacheRead  float64 `json:"cacheRead"`
		CacheWrite float64 `json:"cacheWrite"`
	} `json:"cost"`
}

func main() {
	src := flag.String("src", "", "published image-models.generated.js or an OpenRouter response .json file")
	out := flag.String("out", "ai/image_models_generated.go", "generated Go output")
	flag.Parse()
	if *src == "" {
		fatal(fmt.Errorf("-src is required"))
	}
	models, err := load(*src)
	if err != nil {
		fatal(err)
	}
	data, err := render(models)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		fatal(err)
	}
	fmt.Fprintf(os.Stderr, "gen-image-models: wrote %d models to %s\n", len(models), *out)
}

func load(path string) ([]imageModel, error) {
	if filepath.Ext(path) == ".json" {
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		if !json.Valid(data) {
			return nil, fmt.Errorf("invalid JSON in %s", path)
		}
		models, err := parseOpenRouterImageModels(data, true)
		if err != nil {
			return nil, err
		}
		// The parser preserves API order; file generation sorts and replaces duplicate IDs like Object.fromEntries.
		byID := make(map[string]imageModel, len(models))
		for _, model := range models {
			byID[model.ID] = model
		}
		models = models[:0]
		for _, id := range sortedKeys(byID) {
			models = append(models, byID[id])
		}
		return models, nil
	}
	script := `import { pathToFileURL } from "node:url";
const mod = await import(pathToFileURL(process.argv[1]).href);
process.stdout.write(JSON.stringify(mod.IMAGE_MODELS));`
	cmd := exec.Command("node", "--input-type=module", "-e", script, path)
	data, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("import published image catalog: %w\n%s", err, data)
	}
	var providers map[string]map[string]imageModel
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&providers); err != nil {
		return nil, fmt.Errorf("decode image catalog: %w", err)
	}
	providerNames := sortedKeys(providers)
	var out []imageModel
	for _, provider := range providerNames {
		ids := sortedKeys(providers[provider])
		for _, id := range ids {
			model := providers[provider][id]
			if model.ID != id || model.Provider != provider {
				return nil, fmt.Errorf("catalog key %s/%s disagrees with model %s/%s", provider, id, model.Provider, model.ID)
			}
			out = append(out, model)
		}
	}
	return out, nil
}

func render(models []imageModel) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by gen-image-models. DO NOT EDIT.\n")
	b.WriteString("package ai\n\n")
	fmt.Fprintf(&b, "// GeneratedImageModels is the static image model catalog (%d entries).\n", len(models))
	b.WriteString("var GeneratedImageModels = []ImagesModel{\n")
	for _, model := range models {
		fmt.Fprintf(&b, "{ID:%q, Name:%q, API:ImagesAPI(%q), Provider:ImagesProviderId(%q), BaseURL:%q,", model.ID, model.Name, model.API, model.Provider, model.BaseURL)
		if len(model.Headers) > 0 {
			b.WriteString(" Headers:map[string]string{")
			for _, key := range sortedKeys(model.Headers) {
				fmt.Fprintf(&b, "%q:%q,", key, model.Headers[key])
			}
			b.WriteString("},")
		}
		fmt.Fprintf(&b, " Input:%#v, Output:%#v, Cost:ImagesCost{Input:%v, Output:%v, CacheRead:%v, CacheWrite:%v}},\n",
			model.Input, model.Output, model.Cost.Input, model.Cost.Output, model.Cost.CacheRead, model.Cost.CacheWrite)
	}
	b.WriteString("}\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated catalog: %w", err)
	}
	return formatted, nil
}

func sortedKeys[V any](values map[string]V) []string {
	out := make([]string, 0, len(values))
	for key := range values {
		out = append(out, key)
	}
	slices.Sort(out)
	return out
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen-image-models:", err)
	os.Exit(1)
}
