package ai

import (
	"encoding/json"
	"net/http"
	"os"
	"testing"
)

// The reviewed URL vectors are generated by Node's URL constructor with: node testdata/mistral-url-grid.mjs > testdata/mistral-url-grid.json.
func TestPairReviewMistralURLDifferential(t *testing.T) {
	var rows []struct {
		Base, Want string
		Invalid    bool
	}
	data, err := os.ReadFile("testdata/mistral-url-grid.json")
	if err != nil {
		t.Fatal(err)
	}
	if err = json.Unmarshal(data, &rows); err != nil {
		t.Fatal(err)
	}
	for _, tc := range rows {
		t.Run(tc.Base, func(t *testing.T) {
			got, err := mistralChatCompletionsURL(tc.Base)
			if (err != nil) != tc.Invalid || !tc.Invalid && got != tc.Want {
				t.Fatalf("base=%q: got %q,%v want %q invalid=%v", tc.Base, got, err, tc.Want, tc.Invalid)
			}
			called := false
			provider := NewMistralProvider(MistralConfig{APIKey: "fixture", Model: "model", BaseURL: tc.Base})
			stream, err := provider.Stream(t.Context(), mistralUpstreamContext(), StreamOptions{Fetch: &http.Client{Transport: FetchFunction(func(request *http.Request) (*http.Response, error) {
				called = true
				if got := request.URL.String(); got != tc.Want {
					t.Errorf("fetch URL=%q want=%q", got, tc.Want)
				}
				return mistralUpstreamSSE(mistralUpstreamTerminal), nil
			})}})
			if tc.Invalid {
				if err == nil || called {
					t.Fatalf("invalid URL reached fetch: called=%t err=%v", called, err)
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if result := stream.Result(); !called || result.StopReason != StopReasonStop {
				t.Fatalf("called=%t result=%+v", called, result)
			}
		})
	}
}
