// Command noderuntimegen packages the Node runtime and its content identity reproducibly.
package main

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/klauspost/compress/zstd"
)

func main() {
	root := flag.String("root", "runtime-node", "runtime source directory")
	archive := flag.String("archive", "runtime-node.zip", "archive output")
	metadata := flag.String("metadata", "runtime_node_digest_generated.go", "Go digest output")
	flag.Parse()
	if err := generate(*root, *archive, *metadata); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(root, archive, metadata string) error {
	var buffer bytes.Buffer
	writer := zip.NewWriter(&buffer)
	writer.RegisterCompressor(zstd.ZipMethodWinZip, zstd.ZipCompressor(zstd.WithEncoderConcurrency(1)))
	digest := sha256.New()
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		relative = filepath.ToSlash(relative)
		// Match runtime-node/*.mjs, runtime-node/harness and all:runtime-node/shims.
		if relative == "." {
			return nil
		}
		inShims := relative == "shims" || strings.HasPrefix(relative, "shims/")
		inHarness := relative == "harness" || strings.HasPrefix(relative, "harness/")
		if !inShims && (!inHarness || strings.HasPrefix(entry.Name(), ".") || strings.HasPrefix(entry.Name(), "_")) {
			if entry.IsDir() {
				return filepath.SkipDir
			}
			if strings.Contains(relative, "/") || !strings.HasSuffix(relative, ".mjs") {
				return nil
			}
		}
		if entry.IsDir() {
			return nil
		}
		if !entry.Type().IsRegular() {
			return fmt.Errorf("runtime source is not a regular file: %s", path)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		name := "runtime-node/" + relative
		digest.Write([]byte(name))
		digest.Write(data)
		header := &zip.FileHeader{Name: name, Method: zstd.ZipMethodWinZip}
		header.SetMode(0o644)
		out, err := writer.CreateHeader(header)
		if err != nil {
			return err
		}
		_, err = out.Write(data)
		return err
	})
	if err != nil {
		return err
	}
	if err := writer.Close(); err != nil {
		return err
	}
	source, err := format.Source(fmt.Appendf(nil, "// Code generated by go generate ./coding/extension/host/subprocess; DO NOT EDIT.\n\npackage subprocess\n\nconst nodeRuntimeHash = %q\n", string(digest.Sum(nil))))
	if err != nil {
		return err
	}
	if err := writeGenerated(archive, buffer.Bytes()); err != nil {
		return err
	}
	return writeGenerated(metadata, source)
}

func writeGenerated(path string, data []byte) error {
	if current, err := os.ReadFile(path); err == nil && bytes.Equal(current, data) {
		return nil
	}
	file, err := os.CreateTemp(filepath.Dir(path), ".node-runtime-*")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(file.Name()) }()
	if err := file.Chmod(0o644); err != nil {
		_ = file.Close()
		return err
	}
	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(file.Name(), path)
}
