// Command gentables extracts the static lookup tables from upstream pi's
// tui/src/latex.ts into Go source (symbols.go), so the LaTeX->Unicode port
// never hand-transcribes ~230 symbol rows. Re-run after an upstream bump with:
//
//	go run ./internal/latex/gentables
//
// It reads the pinned mirror at .upstream/current and writes internal/latex/symbols.go.
package main

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

const upstreamPath = ".upstream/current/packages/tui/src/latex.ts"
const outPath = "internal/latex/symbols.go"

// recordTables map a LaTeX token to its Unicode replacement.
var recordTables = []string{"SYMBOLS", "NEGATED_SYMBOLS", "BLACKBOARD", "SUPERSCRIPTS", "SUBSCRIPTS", "ACCENTS"}

// setTables are membership sets keyed by LaTeX token.
var setTables = []string{
	"NAMED_OPERATORS", "LIMIT_OPERATORS", "DISPLAY_LIMIT_SYMBOLS",
	"SPACING_COMMANDS", "NEGATIVE_SPACING_COMMANDS", "IGNORED_COMMANDS",
	"SIZE_COMMANDS", "PLAIN_WRAPPERS", "RELATION_COMMANDS", "FONT_SWITCH_COMMANDS",
}

func main() {
	src, err := os.ReadFile(upstreamPath)
	if err != nil {
		fail(err)
	}
	text := string(src)

	var b strings.Builder
	b.WriteString("// Code generated by internal/latex/gentables; DO NOT EDIT.\n")
	b.WriteString("// Source: upstream pi tui/src/latex.ts (see coding/upstream.go for the pinned version).\n\n")
	b.WriteString("package latex\n\n")

	for _, name := range recordTables {
		entries, err := parseRecord(text, name)
		if err != nil {
			fail(fmt.Errorf("%s: %w", name, err))
		}
		writeRecord(&b, goName(name), entries)
	}
	for _, name := range setTables {
		items, err := parseSet(text, name)
		if err != nil {
			fail(fmt.Errorf("%s: %w", name, err))
		}
		writeSet(&b, goName(name), items)
	}

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d record tables, %d set tables)\n", outPath, len(recordTables), len(setTables))
}

// blockBody returns the text between the first `{`/`[` after the table name and
// its matching close, so entries can be scanned without swallowing later tables.
func blockBody(text, name string, open, close byte) (string, error) {
	idx := strings.Index(text, name)
	if idx < 0 {
		return "", fmt.Errorf("table not found")
	}
	start := strings.IndexByte(text[idx:], open)
	if start < 0 {
		return "", fmt.Errorf("no opening %q", string(open))
	}
	start += idx
	depth := 0
	for i := start; i < len(text); i++ {
		switch text[i] {
		case open:
			depth++
		case close:
			depth--
			if depth == 0 {
				return text[start+1 : i], nil
			}
		}
	}
	return "", fmt.Errorf("unterminated block")
}

var (
	recordEntryRE = regexp.MustCompile(`(?m)^\s*(?:"((?:[^"\\]|\\.)*)"|([A-Za-z][A-Za-z0-9]*))\s*:\s*"((?:[^"\\]|\\.)*)"\s*,?\s*$`)
	// setEntryRE matches every quoted item in a Set body, whether one-per-line
	// (multiline sets) or inline (NEGATIVE_SPACING_COMMANDS is on a single line).
	setEntryRE = regexp.MustCompile(`"((?:[^"\\]|\\.)*)"`)
)

type kv struct{ k, v string }

func parseRecord(text, name string) ([]kv, error) {
	body, err := blockBody(text, name, '{', '}')
	if err != nil {
		return nil, err
	}
	var out []kv
	for _, m := range recordEntryRE.FindAllStringSubmatch(body, -1) {
		key := m[2] // bareword identifier key
		if key == "" {
			key = unquoteJS(m[1]) // quoted key (e.g. "<", "∈")
		}
		out = append(out, kv{k: key, v: unquoteJS(m[3])})
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no entries parsed")
	}
	return out, nil
}

func parseSet(text, name string) ([]string, error) {
	body, err := blockBody(text, name, '[', ']')
	if err != nil {
		return nil, err
	}
	var out []string
	for _, m := range setEntryRE.FindAllStringSubmatch(body, -1) {
		out = append(out, unquoteJS(m[1]))
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no entries parsed")
	}
	return out, nil
}

// unquoteJS decodes a JS/TS double-quoted string body (escapes, \uXXXX, \u{...}).
func unquoteJS(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] != '\\' {
			b.WriteByte(s[i])
			continue
		}
		i++
		if i >= len(s) {
			break
		}
		switch s[i] {
		case 'n':
			b.WriteByte('\n')
		case 't':
			b.WriteByte('\t')
		case 'r':
			b.WriteByte('\r')
		case '0':
			b.WriteByte(0)
		case 'u':
			if i+1 < len(s) && s[i+1] == '{' {
				end := strings.IndexByte(s[i:], '}')
				n, _ := strconv.ParseInt(s[i+2:i+end], 16, 32)
				b.WriteRune(rune(n))
				i += end
			} else if i+4 < len(s)+1 {
				n, _ := strconv.ParseInt(s[i+1:i+5], 16, 32)
				b.WriteRune(rune(n))
				i += 4
			}
		default:
			b.WriteByte(s[i])
		}
	}
	return b.String()
}

func writeRecord(b *strings.Builder, goVar string, entries []kv) {
	fmt.Fprintf(b, "var %s = map[string]string{\n", goVar)
	for _, e := range entries {
		fmt.Fprintf(b, "\t%s: %s,\n", strconv.Quote(e.k), strconv.Quote(e.v))
	}
	b.WriteString("}\n\n")
}

func writeSet(b *strings.Builder, goVar string, items []string) {
	fmt.Fprintf(b, "var %s = map[string]bool{\n", goVar)
	for _, it := range items {
		fmt.Fprintf(b, "\t%s: true,\n", strconv.Quote(it))
	}
	b.WriteString("}\n\n")
}

// goName lowercases the leading run so the generated identifier is unexported
// (latexSymbols, latexNamedOperators, ...), keeping the table private to the package.
func goName(tsName string) string {
	parts := strings.Split(strings.ToLower(tsName), "_")
	var b strings.Builder
	b.WriteString("latex")
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gentables:", err)
	os.Exit(1)
}
