#!/usr/bin/env python3
"""Build ICU 78.3's four byte dictionaries and Unicode 17 complex-context sets."""
import hashlib
import pathlib
import struct
import sys

ROOT = pathlib.Path(__file__).resolve().parent
SOURCE = pathlib.Path(sys.argv[1])
DICTIONARIES = [
    ("thai", "thaidict", "3166abde40c0f44ab91c28f5ce96d7d1472cb7882e1c0bda0a72f8f69dba4274", 0xE00),
    ("lao", "laodict", "3c876934a3fa81031d2333525eafaca6a7c9f842e3b98f18c38880420afb5d36", 0xE80),
    ("khmer", "khmerdict", "87bee2d17cd5148aa36957eb05409eefc124de8ad519b81b789298ef3e60b5d9", 0x1780),
    ("burmese", "burmesedict", "61d8abc3d9102b2f9bf0c9f44db0d7ab89b18172d8cd26832e4c83174bd8673b", 0x1000),
]


def verified(name, digest):
    data = (SOURCE / name).read_bytes()
    if hashlib.sha256(data).hexdigest() != digest:
        raise SystemExit("unexpected source hash: " + name)
    return data.decode("utf-8-sig")


notices = []
for name, file, digest, base in DICTIONARIES:
    rows, notice = [], []
    for line in verified(file + ".txt", digest).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            if not rows:
                notice.append(line.removeprefix("#").lstrip())
            continue
        # ICU BUILDRULES.py uses gendict --bytes --transform offset-<base>.
        values = [0xFF if c == "\u200d" else 0xFE if c == "\u200c" else ord(c) - base for c in line]
        if any(not 0 <= v <= 0xFD for c, v in zip(line, values) if c not in "\u200c\u200d"):
            raise SystemExit("word outside ICU transform range: " + line)
        rows.append(bytes(values))
    rows.sort()
    if len(set(rows)) != len(rows):
        raise SystemExit("duplicate dictionary word")
    offsets = [0]
    for word in rows:
        offsets.append(offsets[-1] + len(word))
    if max(len(rows), offsets[-1]) > 0xFFFFFFFF:
        raise SystemExit("dictionary offsets exceed uint32")
    # Current unversioned byte index: uint32 count, count+1 uint32 offsets, word bytes.
    encoded = struct.pack("<I", len(rows)) + struct.pack("<" + "I" * len(offsets), *offsets) + b"".join(rows)
    (ROOT / (name + "_dictionary.bin")).write_bytes(encoded)
    notices.append(file + ".txt (ICU release-78.3)\n\n" + "\n".join(notice).strip())
    print(f"{name}: {len(rows)} entries, {len(encoded)} bytes, sha256:{digest}")
(ROOT.parent.parent / "LICENSES/LicenseRef-ICU-SEA.txt").write_text("\n\n".join(notices) + "\n", encoding="utf8")


def properties(name, digest):
    result = {}
    for line in verified(name, digest).splitlines():
        data, _, comment = line.partition("#")
        if not data.strip():
            continue
        span, prop = map(str.strip, data.split(";"))
        bounds = [int(v, 16) for v in span.split("..")]
        for c in range(bounds[0], bounds[-1] + 1):
            result[c] = (prop, comment.strip().split()[0] if comment.strip() else "")
    return result


lb = properties("LineBreak.txt", "e6a18fa91f8f6a6f8e534b1d3f128c21ada45bfe152eb6b1bcc5e15fd8ac92e6")
wb = properties("WordBreakProperty.txt", "72274cac1e6b919507db35655c3e175aa27274668a1ece95c28d2069f2ad9852")
gb = properties("GraphemeBreakProperty.txt", "d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89")
scripts = properties("Scripts.txt", "9f5e50d3abaee7d6ce09480f325c706f485ae3240912527e651954d2d6b035bf")
# ICU word.txt: ALetterPlus includes ComplexContext - Extend - Control.
# Low bits select a dictionary engine; high bits encode ALetterPlus and fMarkSet.
ranges = []
for c, (prop, category) in sorted(lb.items()):
    if prop != "SA":
        continue
    script = scripts.get(c, ("",))[0]
    engine = {"Thai": 1, "Lao": 2, "Khmer": 3, "Myanmar": 4}.get(script, 0)
    if engine and not 0x800 <= c <= 0xFFFF:
        raise SystemExit("dictionary engine span violates BMP / three-byte UTF-8 indexing")
    flags = engine
    if wb.get(c, ("",))[0] != "Extend" and gb.get(c, ("",))[0] != "Control":
        flags |= 8
    if category.startswith("M"):
        flags |= 16
    if ranges and ranges[-1][1] + 1 == c and ranges[-1][2] == flags:
        ranges[-1][1] = c
    else:
        ranges.append([c, c, flags])
out = "// Code generated by generate_sea_dictionary.py from Unicode 17.0.0; DO NOT EDIT.\n\npackage wordsegmenter\n\nvar complexContextRanges = [...][3]rune{\n"
for lo, hi, flags in ranges:
    out += f"\t{{0x{lo:x}, 0x{hi:x}, {flags}}},\n"
out += "}\n\n"
# ICU word.txt removes dictionaryCJK from ALetter and Han from Extend. The flags also encode its two extra chaining rules and rule-status tail classes.
rule_ranges = []
for c in sorted(set(scripts) | set(wb)):
    script = scripts.get(c, ("",))[0]
    prop = wb.get(c, ("",))[0]
    kana_kanji = script in ("Han", "Hiragana") or prop == "Katakana"
    hangul = 0xAC00 <= c <= 0xD7A3
    dictionary = script in ("Han", "Hiragana", "Katakana") or c in (0x30FC, 0xFF70, 0xFF9E, 0xFF9F)
    excluded = (kana_kanji or hangul) and prop == "ALetter" or script == "Han" and prop == "Extend"
    exfm = prop in ("Extend", "Format", "ZWJ") and not (script == "Han" and prop == "Extend")
    flags = int(kana_kanji) | int(hangul) * 2 | int(dictionary) * 4 | int(excluded) * 8 | int(exfm) * 16 | int(prop == "ExtendNumLet") * 32 | int(prop == "Hebrew_Letter") * 64
    if not flags:
        continue
    if rule_ranges and rule_ranges[-1][1] + 1 == c and rule_ranges[-1][2] == flags:
        rule_ranges[-1][1] = c
    else:
        rule_ranges.append([c, c, flags])
out += "var wordRuleRanges = [...][3]rune{\n"
for lo, hi, flags in rule_ranges:
    out += f"\t{{0x{lo:x}, 0x{hi:x}, {flags}}},\n"
out += "}\n\n"
# rbbi.cpp getLanguageBreakEngine gives a $dictionary character without an engine to brkeng.cpp UnhandledEngine,
# which then claims that character's entire Script value. Only those scripts can become its handled set.
engine_scripts = {"Thai", "Lao", "Khmer", "Myanmar"}
cjk_engine = lambda c: scripts.get(c, ("",))[0] in ("Han", "Hiragana", "Katakana") or c in (0x30FC, 0xFF70, 0xFF9E, 0xFF9F)
unhandled = set()
for c in range(0x110000):
    script, prop = scripts.get(c, ("Unknown",))[0], wb.get(c, ("",))[0]
    sa = lb.get(c, ("",))[0] == "SA"
    dictionary = sa or script in ("Han", "Hiragana") or prop == "Katakana" or 0xAC00 <= c <= 0xD7A3
    if dictionary and not (sa and script in engine_scripts) and not cjk_engine(c):
        unhandled.add(script)
script_ids = {name: i + 1 for i, name in enumerate(sorted(unhandled))}
script_ranges = []
for c, (script, _) in sorted(scripts.items()):
    if script not in script_ids:
        continue
    if script_ranges and script_ranges[-1][1] + 1 == c and script_ranges[-1][2] == script_ids[script]:
        script_ranges[-1][1] = c
    else:
        script_ranges.append([c, c, script_ids[script]])
out += "// unhandledScriptRanges maps each code point of a Script that UnhandledEngine can claim to a small script ID: " + ", ".join(f"{i}={name}" for name, i in script_ids.items()) + ".\n"
out += "var unhandledScriptRanges = [...][3]rune{\n"
for lo, hi, script in script_ranges:
    out += f"\t{{0x{lo:x}, 0x{hi:x}, {script}}},\n"
out += "}\n"
(ROOT / "rule_data.go").write_text(out, encoding="utf8")
