// Generate the scalar word-like set from the pinned Intl.Segmenter rule-status oracle.
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
if(process.versions.icu!=='78.3'||process.versions.unicode!=='17.0')throw new Error('Expected ICU 78.3 / Unicode 17.0');
const segmenter=new Intl.Segmenter(undefined,{granularity:'word'});
const ranges=[];let start=-1;
for(let cp=0;cp<=0x110000;cp++){
 const word=cp<0x110000&&segmenter.segment(String.fromCodePoint(cp))[Symbol.iterator]().next().value.isWordLike;
 if(word&&start<0)start=cp;
 if(!word&&start>=0){ranges.push([start,cp-1]);start=-1;}
}
let source='// Code generated by node internal/wordsegmenter/generate_word_like.mjs; DO NOT EDIT.\n// Intl.Segmenter ICU 78.3 / Unicode 17.0 single-code-point word rule status.\npackage wordsegmenter\n\nvar wordLikeRanges = [...][2]rune{\n';
for(const [a,b]of ranges)source+=`{0x${a.toString(16)},0x${b.toString(16)}},\n`;
source+='}\n';
fs.writeFileSync(fileURLToPath(new URL('./word_like_data.go',import.meta.url)),source);
console.log(ranges.length,'ranges generated');
