#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright Hewlett Packard Enterprise Development LP
# SPDX-License-Identifier: MIT
"""Rewrite the documentation/evidence section of the repository layout."""

import argparse
import json
from pathlib import Path, PurePosixPath
import posixpath
import re
import subprocess
import sys
import tomllib

import docs_prose
import plan

GO_MOVES = plan.package_moves()
DOC_MOVES = {
    "CODE_OF_CONDUCT.md": ".github/CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md": ".github/CONTRIBUTING.md",
    "SECURITY.md": ".github/SECURITY.md",
    "SUPPORT.md": ".github/SUPPORT.md",
    "GOVERNANCE.md": "docs/project/GOVERNANCE.md",
    "MAINTAINERS.md": "docs/project/MAINTAINERS.md",
    "QUICKSTART.md": "docs/project/QUICKSTART.md",
}
RELATIVE_PIN_PATHS = {
    "parity/interface-extractor/test/inventory.test.mjs": "../../../coding/pigversion/pigversion.go",
    "parity/interface-extractor/test/correspondence-inventory.test.mjs": "../../../coding/pigversion/pigversion.go",
}
MOVED_ORACLE_ROOTS = {
    "agent/testdata/tool-validation-oracle.mjs": "'../../extensions/sdk-ts/node_modules/@earendil-works/pi-coding-agent/'",
    "tui/testdata/color_detection.mjs": '"../../extensions/sdk-ts/node_modules/@earendil-works/pi-coding-agent/"',
    "agent/harness/session/testdata/generate-fork-snapshots.mjs": "'../../../../.upstream/current/packages/agent/src/harness/session/fork.ts'",
    "agent/harness/testdata/telemetry-schema.mjs": "'../../..'",
}
REQUIRED = ("AGENTS.md", "PORT_MAP.md", "DIVERGENCES.md", "CHANGELOG.md", "README.md", "go.mod")
PARITY_SUFFIXES = {".toml", ".json", ".tsv", ".sh", ".mjs", ".js", ".ts", ".py", ".yaml", ".yml"}
# These are regenerated by their owners, never edited as if they were ledgers.
GENERATED = re.compile(r"parity/interfaces/(?:pig-go\.json|(?:recommendations|upstream|upstream-tests|behavior-inputs|delta|custom-factory-call-surface-draft)-v[^/]+\.json)$")
CHANGELOG_BULLET = "- Keep repository documentation, governance links, and parity evidence paths aligned with the internal Go package layout."
GRAPH_SOURCE = "docs/knowledge-graph/pig.graph.json"
GRAPH_GENERATOR = "automation/gen/gen-knowledge-graph.py"
GRAPH_OUTPUTS = (
    "docs/knowledge-graph/pig-knowledge-graph.jsonld",
    "docs/knowledge-graph/pig.mmd",
    "docs/site/docs/knowledge-graph.md",
    "internal/pigdocs/content/knowledge-graph.md",
    "internal/pigdocs/content/troubleshooting.md",
)
MODULE = "github.com/MichaelKinsy/PiG/"
REPO_URL = re.compile(r"((?:https://github\.com/MichaelKinsy/PiG/(?:blob|tree)/(?:main|master|HEAD)/|https://raw\.githubusercontent\.com/MichaelKinsy/PiG/(?:main|master|HEAD)/))(.+)")
URL = re.compile(r"(?:https?://|mailto:)[^\s<>`\"')]+")
# Relative Markdown destinations, including reference definitions and HTML attributes.
DESTINATION = re.compile(r"(?P<lead>\]\(<?|^\s*\[[^\]\n]+\]:\s*<?|(?:href|src)=[\"'])(?P<target>[^\s<>\"')]+)", re.MULTILINE)
CODE = re.compile(r"(?<!`)`([^`\n]+)`(?!`)")
PATH_TOKEN = re.compile(
    r"(?<![\w./@-])(?<!pkg:)(?P<prefix>(?:\.\./)+|\./)?"
    r"(?P<path>(?:agent|ai|coding|tui)(?:/[^\s`\"'()<>\[\],;|#?:{}]*|(?=[:\s`\"')]|$))|"
    + "|".join(re.escape(name) for name in DOC_MOVES)
    + r")"
)


def git(root, *args):
    return subprocess.check_output(["git", "-C", str(root), *args], text=True)


def move_path(path):
    if path in DOC_MOVES:
        return DOC_MOVES[path]
    for old, new in GO_MOVES.items():
        if path == old or path.startswith(old + "/"):
            return new + path[len(old):]
    return path


def original_path(path):
    for old, new in DOC_MOVES.items():
        if path == new:
            return old
    for old, new in GO_MOVES.items():
        if path.startswith(new + "/"):
            return old + path[len(new):]
    return path


def owned(path):
    parts = PurePosixPath(path).parts
    if "node_modules" in parts or path.startswith((".upstream/", "automation/")):
        return False
    if "/runtime-node/shims/" in path or path in ("parity/coverage.md", "parity/normalization-inventory.json") or path in GRAPH_OUTPUTS:
        return False
    if path == GRAPH_SOURCE or original_path(path) in MOVED_ORACLE_ROOTS:
        return True
    if path.endswith(".md"):
        return True
    return path.startswith("parity/") and PurePosixPath(path).suffix in PARITY_SUFFIXES and not GENERATED.fullmatch(path)


class Rewriter:
    def __init__(self, root, tracked):
        self.root = root
        self.known = set()
        for name in tracked:
            for alias in (name, original_path(name), move_path(name)):
                self.known.add(alias)
                self.known.update(str(p) for p in PurePosixPath(alias).parents)

    def known_path(self, name):
        if name == ".." or name.startswith("../"):
            return False
        # The oracle is often an untracked symlink, but is never an edit target.
        return name in self.known or (name.startswith(".upstream/") and (self.root / name).exists())

    def relative(self, target, document):
        if re.match(r"(?:[\w+.-]+:|/|#)", target):
            return self.url(target)
        path, mark, fragment = target.partition("#")
        path, query_mark, query = path.partition("?")
        current = posixpath.normpath(posixpath.join(posixpath.dirname(document), path))
        old_doc = original_path(document)
        old = posixpath.normpath(posixpath.join(posixpath.dirname(old_doc), path))
        if self.known_path(current):
            resolved = move_path(current)
        elif self.known_path(old):
            resolved = move_path(old)
        else:
            return target
        if resolved == current:
            return target
        result = posixpath.relpath(resolved, posixpath.dirname(document) or ".")
        if path.endswith("/"):
            result += "/"
        return result + query_mark + query + mark + fragment

    @staticmethod
    def url(value):
        match = REPO_URL.fullmatch(value)
        if not match:
            return value
        path, mark, fragment = match[2].partition("#")
        return match[1] + move_path(path) + mark + fragment

    def references(self, text, document=None):
        # Full Go import paths are unambiguous. Other projects' URLs are protected by text().
        for old, new in GO_MOVES.items():
            text = re.sub(re.escape(MODULE + old) + r"(?=/|[\s\"'`)]|$)", MODULE + new, text)

        def replace(match):
            prefix, path = match["prefix"] or "", match["path"]
            if prefix.startswith("../"):
                return self.relative(match[0], document) if document else match[0]
            if path in GO_MOVES and not prefix:
                return match[0]  # Ordinary prose and upstream package names are not Go paths.
            if re.match(r"(?:agent|ai|coding|tui)/(?:src|test|dist)(?:/|$)", path):
                return match[0]  # Abbreviated upstream source paths in ledger rationale.
            if path.rstrip(".").endswith((".ts", ".js", ".mjs")) and not self.known_path(path.rstrip(".")):
                return match[0]
            return prefix + move_path(path)

        return PATH_TOKEN.sub(replace, text)

    def text(self, text, document, markdown=True):
        original = original_path(document)
        if document != original and original in MOVED_ORACLE_ROOTS:
            old = MOVED_ORACLE_ROOTS[original]
            new = old.replace("../", "../../", 1)
            if text.count(old) + text.count(new) != 1:
                raise ValueError(f"{document}: expected exactly one relative oracle root")
            text = text.replace(old, new)
        if document in RELATIVE_PIN_PATHS:
            old = RELATIVE_PIN_PATHS[document]
            new = "../../../" + move_path(old.removeprefix("../../../"))
            if old == new:
                pass
            elif text.count(old) + text.count(new) != 1:
                raise ValueError(f"{document}: expected exactly one relative Pi pin path")
            text = text.replace(old, new)
        protected = []

        def hold(value):
            protected.append(value)
            return f"\x00layout-docs-{len(protected) - 1}\x00"

        if "\x00" in text:
            raise ValueError(f"NUL in text file: {document}")
        # Resolve destinations before rewriting labels. This also rebases links out of moved documents.
        if markdown:
            text = DESTINATION.sub(lambda m: m["lead"] + hold(self.relative(m["target"], document)), text)
            def code_reference(match):
                value = match[1]
                if not value.startswith(("../", "./")) or " " in value:
                    return match[0]
                rewritten = self.relative(value, document)
                current = posixpath.normpath(posixpath.join(posixpath.dirname(document), value))
                value = self.references(value) if rewritten == value and value.startswith("./") and not self.known_path(current) else rewritten
                if not value.startswith(("../", "./")):
                    value = "./" + value
                return "`" + hold(value) + "`"

            text = CODE.sub(code_reference, text)
        text = URL.sub(lambda m: hold(self.url(m[0])), text)
        text = self.references(text, document)
        # Restore in reverse order: a protected destination can contain an earlier placeholder.
        for i in reversed(range(len(protected))):
            text = text.replace(f"\x00layout-docs-{i}\x00", protected[i])
        return text


def changelog(text):
    if CHANGELOG_BULLET in text:
        return text
    section = re.search(r"(?ms)^## \[Unreleased\][^\n]*\n(?P<body>.*?)(?=^## |\Z)", text)
    if not section:
        raise ValueError("CHANGELOG.md: expected [Unreleased] section")
    fixed = re.search(r"(?m)^### Fixed\n", section["body"])
    if not fixed:
        raise ValueError("CHANGELOG.md: expected [Unreleased] Fixed section")
    at = section.start("body") + fixed.end()
    return text[:at] + "\n" + CHANGELOG_BULLET + "\n" + text[at:]


def sort_format_fields(text):
    preamble, *blocks = re.split(r"(?m)(?=^\[\[fields\]\]$)", text)
    ids = [tomllib.loads(block)["fields"][0]["id"] for block in blocks]
    if not ids or len(set(ids)) != len(ids):
        raise ValueError("parity/format-versions.toml: expected unique field IDs")
    ordered = [block.rstrip("\n") for _, block in sorted(zip(ids, blocks))]
    return preamble + "\n\n".join(ordered) + "\n"


def reject_symlink(root, name):
    path = root
    for part in PurePosixPath(name).parts:
        path = path / part
        if path.is_symlink():
            raise ValueError(f"expected tracked regular file: {name}; symlink at {path.relative_to(root)}")


def apply(root, keep_public_libraries=False):
    if Path(git(root, "rev-parse", "--show-toplevel").strip()).resolve() != root:
        raise ValueError("argument must be the repository root")
    tracked = set(git(root, "ls-files", "-z").rstrip("\0").split("\0"))
    moves = []
    for old, new in DOC_MOVES.items():
        reject_symlink(root, old)
        reject_symlink(root, new)
        src, dst = root / old, root / new
        if src.exists() and dst.exists():
            raise ValueError(f"both source and destination exist: {old}, {new}")
        present = old if src.exists() else new
        if present not in tracked or not (root / present).is_file() or (root / present).is_symlink():
            raise ValueError(f"expected tracked regular file at {old} or {new}")
        if present == old:
            moves.append((old, new))
    required = REQUIRED + tuple(RELATIVE_PIN_PATHS) + ((GRAPH_GENERATOR,) + GRAPH_OUTPUTS if GRAPH_SOURCE in tracked else ())
    for name in required:
        reject_symlink(root, name)
        if name not in tracked or not (root / name).is_file() or (root / name).is_symlink():
            raise ValueError(f"expected tracked regular file: {name}")
    rewriter = Rewriter(root, tracked)
    changes = []
    for name in sorted(tracked):
        if not owned(name):
            continue
        reject_symlink(root, name)
        path = root / name
        if not path.is_file() or path.is_symlink():
            raise ValueError(f"expected tracked regular file: {name}")
        before = path.read_bytes().decode("utf-8")
        destination = DOC_MOVES.get(name, name)
        after = rewriter.text(docs_prose.rewrite_prose(before, name, keep_public_libraries), destination, name.endswith(".md"))
        if name == "CHANGELOG.md":
            after = changelog(after)
        if name == "parity/format-versions.toml":
            after = sort_format_fields(after)
        if after != before:
            changes.append((destination, after))
    # Validate every input and compute every edit before the first mutation.
    for old, new in moves:
        (root / new).parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(["git", "-C", str(root), "mv", "--", old, new], check=True)
    for name, content in changes:
        (root / name).write_bytes(content.encode("utf-8"))
    rewritten = [name for name, _ in changes]
    if GRAPH_SOURCE in tracked:
        before = {name: (root / name).read_bytes() for name in GRAPH_OUTPUTS}
        subprocess.run([sys.executable, "-B", str(root / GRAPH_GENERATOR)], cwd=root, check=True, stdout=subprocess.PIPE)
        rewritten.extend(name for name in GRAPH_OUTPUTS if (root / name).read_bytes() != before[name])
    return {"section": "docs", "moved": [new for _, new in moves], "rewritten": sorted(rewritten)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--keep-public-libraries", action="store_true")
    parser.add_argument("root", nargs="?", default=".")
    args = parser.parse_args()
    try:
        with plan.selected(globals(), GO_MOVES=plan.package_moves(args.keep_public_libraries)):
            report = apply(Path(args.root).resolve(), args.keep_public_libraries)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"layout-docs: {error}", file=sys.stderr)
        return 1
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
