// Code generated by go generate ./coding/extension/host/subprocess; DO NOT EDIT.

package subprocess

const nodeRuntimeHash = "]#]$\xb4\xadɳ\b\xab\xa7& \a\xc91{9\xccB\x8c\xf9\x968\x9a-\x8f\x97#\x89,\xe6"
